import type { PlanItem, WorkoutRoutine } from '../../store/plannerStore';

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

const TRANSLATIONS: Record<string, {
  nutritionTitle: string;
  nutritionHeader: string;
  workoutTitle: string;
  workoutHeader: string;
  to: string;
  plannedDays: string;
  kcalPerDay: string;
  proteinPerDay: string;
  noMealsPlanned: string;
  generatedBy: string;
  forReferenceOnly: string;
  workoutDays: string;
  totalExercises: string;
  energy: string;
  disclaimer: string;
  rest: string;
  restDayMessage: string;
  sets: string;
  reps: string;
  kcal: string;
  protein: string;
  carbs: string;
  fat: string;
  breakfast: string;
  lunch: string;
  dinner: string;
  snack: string;
  energyLow: string;
  energyNormal: string;
  energyBeast: string;
  dayLabels: Record<string, string>;
}> = {
  es: {
    nutritionTitle: 'FitGO Plan Nutricional',
    nutritionHeader: 'Plan Nutricional Semanal',
    workoutTitle: 'FitGO Rutina Semanal',
    workoutHeader: 'Rutina Semanal de Entrenamiento',
    to: 'al',
    plannedDays: 'Días planificados',
    kcalPerDay: 'kcal / día',
    proteinPerDay: 'Proteína / día',
    noMealsPlanned: 'Sin comidas planificadas para este día',
    generatedBy: 'Generado por FitGO',
    forReferenceOnly: 'Solo para referencia personal',
    workoutDays: 'Días de entreno',
    totalExercises: 'Ejercicios totales',
    energy: 'Energía',
    disclaimer: 'Este plan es generado por inteligencia artificial y NO reemplaza el consejo de un entrenador certificado o médico.',
    rest: 'Descanso',
    restDayMessage: 'Día de descanso — recupera energías 💤',
    sets: 'series',
    reps: 'reps',
    kcal: 'kcal',
    protein: 'Proteína',
    carbs: 'Carbohidratos',
    fat: 'Grasas',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snack: 'Merienda',
    energyLow: '🔋 Agotado',
    energyNormal: '⚡ Normal',
    energyBeast: '🦍 Bestia',
    dayLabels: { Mon: 'Lunes', Tue: 'Martes', Wed: 'Miércoles', Thu: 'Jueves', Fri: 'Viernes', Sat: 'Sábado', Sun: 'Domingo' }
  },
  en: {
    nutritionTitle: 'FitGO Nutrition Plan',
    nutritionHeader: 'Weekly Nutrition Plan',
    workoutTitle: 'FitGO Weekly Workout',
    workoutHeader: 'Weekly Workout Routine',
    to: 'to',
    plannedDays: 'Planned Days',
    kcalPerDay: 'kcal / day',
    proteinPerDay: 'Protein / day',
    noMealsPlanned: 'No meals planned for this day',
    generatedBy: 'Generated by FitGO',
    forReferenceOnly: 'For personal reference only',
    workoutDays: 'Workout Days',
    totalExercises: 'Total Exercises',
    energy: 'Energy',
    disclaimer: 'This plan is generated by artificial intelligence. It does not replace the advice of a certified trainer or doctor. Consult a professional before following this plan.',
    rest: 'Rest',
    restDayMessage: 'Rest day — recover energy 💤',
    sets: 'sets',
    reps: 'reps',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    energyLow: '🔋 Exhausted',
    energyNormal: '⚡ Normal',
    energyBeast: '🦍 Beast',
    dayLabels: { Mon: 'Monday', Tue: 'Tuesday', Wed: 'Wednesday', Thu: 'Thursday', Fri: 'Friday', Sat: 'Saturday', Sun: 'Sunday' }
  },
  fr: {
    nutritionTitle: 'FitGO Plan Nutritionnel',
    nutritionHeader: 'Plan Nutritionnel Hebdomadaire',
    workoutTitle: 'FitGO Routine Hebdomadaire',
    workoutHeader: 'Routine d\'Entraînement Hebdomadaire',
    to: 'au',
    plannedDays: 'Jours planifiés',
    kcalPerDay: 'kcal / jour',
    proteinPerDay: 'Protéines / jour',
    noMealsPlanned: 'Aucun repas prévu pour ce jour',
    generatedBy: 'Généré par FitGO',
    forReferenceOnly: 'Pour référence personnelle uniquement',
    workoutDays: 'Jours d\'entraînement',
    totalExercises: 'Total d\'exercices',
    energy: 'Énergie',
    disclaimer: 'Ce plan est généré par l\'intelligence artificielle. Il ne remplace pas les conseils d\'un entraîneur certifié ou d\'un médecin. Consultez un professionnel avant de suivre ce plan.',
    rest: 'Repos',
    restDayMessage: 'Jour de repos — récupérez de l\'énergie 💤',
    sets: 'séries',
    reps: 'reps',
    kcal: 'kcal',
    protein: 'Protéine',
    carbs: 'Glucides',
    fat: 'Lipides',
    breakfast: 'Petit-déjeuner',
    lunch: 'Déjeuner',
    dinner: 'Dîner',
    snack: 'Collation',
    energyLow: '🔋 Épuisé',
    energyNormal: '⚡ Normal',
    energyBeast: '🦍 Bête',
    dayLabels: { Mon: 'Lundi', Tue: 'Mardi', Wed: 'Mercredi', Thu: 'Jeudi', Fri: 'Vendredi', Sat: 'Samedi', Sun: 'Dimanche' }
  },
  de: {
    nutritionTitle: 'FitGO Ernährungsplan',
    nutritionHeader: 'Wöchentlicher Ernährungsplan',
    workoutTitle: 'FitGO Wöchentliches Training',
    workoutHeader: 'Wöchentlicher Trainingsplan',
    to: 'bis',
    plannedDays: 'Geplante Tage',
    kcalPerDay: 'kcal / Tag',
    proteinPerDay: 'Eiweiß / Tag',
    noMealsPlanned: 'Keine Mahlzeiten für diesen Tag geplant',
    generatedBy: 'Generiert von FitGO',
    forReferenceOnly: 'Nur zur persönlichen Referenz',
    workoutDays: 'Trainingstage',
    totalExercises: 'Übungen insgesamt',
    energy: 'Energie',
    disclaimer: 'Dieser Plan wird durch künstliche Intelligenz generiert. Er ersetzt nicht den Rat eines zertifizierten Trainers oder Arztes. Konsultiere einen Profi, bevor du diesem Plan folgst.',
    rest: 'Erholung',
    restDayMessage: 'Ruhetag — erhole dich und tanke Kraft 💤',
    sets: 'Sätze',
    reps: 'Wdh.',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Kohlenhydrate',
    fat: 'Fett',
    breakfast: 'Frühstück',
    lunch: 'Mittagessen',
    dinner: 'Abendessen',
    snack: 'Snack',
    energyLow: '🔋 Erschöpft',
    energyNormal: '⚡ Normal',
    energyBeast: '🦍 Bestie',
    dayLabels: { Mon: 'Montag', Tue: 'Dienstag', Wed: 'Mittwoch', Thu: 'Donnerstag', Fri: 'Freitag', Sat: 'Samstag', Sun: 'Sonntag' }
  },
  it: {
    nutritionTitle: 'FitGO Piano Nutrizionale',
    nutritionHeader: 'Piano Nutrizionale Settimanale',
    workoutTitle: 'FitGO Scheda Settimanale',
    workoutHeader: 'Scheda di Allenamento Settimanale',
    to: 'a',
    plannedDays: 'Giorni pianificati',
    kcalPerDay: 'kcal / giorno',
    proteinPerDay: 'Proteine / giorno',
    noMealsPlanned: 'Nessun pasto programmato per questo giorno',
    generatedBy: 'Generato da FitGO',
    forReferenceOnly: 'Solo per riferimento personale',
    workoutDays: 'Giorni di allenamento',
    totalExercises: 'Esercizi totali',
    energy: 'Energia',
    disclaimer: 'Questo piano è generato dall\'intelligenza artificiale. Non sostituisce il consiglio di un allenatore certificato o di un medico. Consulta un professionista prima di seguire questo piano.',
    rest: 'Riposo',
    restDayMessage: 'Giorno di riposo — recupera le energie 💤',
    sets: 'serie',
    reps: 'rip.',
    kcal: 'kcal',
    protein: 'Proteine',
    carbs: 'Carboidrati',
    fat: 'Grassi',
    breakfast: 'Colazione',
    lunch: 'Pranzo',
    dinner: 'Cena',
    snack: 'Spuntino',
    energyLow: '🔋 Esaurito',
    energyNormal: '⚡ Normale',
    energyBeast: '🦍 Bestia',
    dayLabels: { Mon: 'Lunedì', Tue: 'Martedì', Wed: 'Mercoledì', Thu: 'Giovedì', Fri: 'Venerdì', Sat: 'Sabato', Sun: 'Domenica' }
  },
  pt: {
    nutritionTitle: 'FitGO Plano Nutricional',
    nutritionHeader: 'Plano Nutricional Semanal',
    workoutTitle: 'FitGO Treino Semanal',
    workoutHeader: 'Rotina de Treino Semanal',
    to: 'a',
    plannedDays: 'Dias planejados',
    kcalPerDay: 'kcal / dia',
    proteinPerDay: 'Proteína / dia',
    noMealsPlanned: 'Nenhuma refeição planejada para este dia',
    generatedBy: 'Gerado por FitGO',
    forReferenceOnly: 'Apenas para referência pessoal',
    workoutDays: 'Dias de treino',
    totalExercises: 'Exercícios totais',
    energy: 'Energia',
    disclaimer: 'Este plano é gerado por inteligência artificial. Não substitui o conselho de um treinador certificado ou médico. Consulte um profissional antes de seguir este plano.',
    rest: 'Descanso',
    restDayMessage: 'Dia de descanso — recupera as energias 💤',
    sets: 'séries',
    reps: 'reps',
    kcal: 'kcal',
    protein: 'Proteína',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    breakfast: 'Café da manhã',
    lunch: 'Almoço',
    dinner: 'Jantar',
    snack: 'Lanche',
    energyLow: '🔋 Esgotado',
    energyNormal: '⚡ Normal',
    energyBeast: '🦍 Bestial',
    dayLabels: { Mon: 'Segunda-feira', Tue: 'Terça-feira', Wed: 'Quarta-feira', Thu: 'Quinta-feira', Fri: 'Sexta-feira', Sat: 'Sábado', Sun: 'Domingo' }
  },
  ru: {
    nutritionTitle: 'FitGO План питания',
    nutritionHeader: 'Еженедельный план питания',
    workoutTitle: 'FitGO Программа тренировок',
    workoutHeader: 'Еженедельная программа тренировок',
    to: 'по',
    plannedDays: 'Запланированные дни',
    kcalPerDay: 'ккал / день',
    proteinPerDay: 'Белки / день',
    noMealsPlanned: 'Нет запланированных приемов пищи на этот день',
    generatedBy: 'Создано FitGO',
    forReferenceOnly: 'Только для личного ознакомления',
    workoutDays: 'Дни тренировок',
    totalExercises: 'Всего упражнений',
    energy: 'Энергия',
    disclaimer: 'Этот план создан искусственным интеллектом. Он не заменяет советы сертифицированного тренера или врача. Проконсультируйтесь с профессионалом, прежде чем следовать этому плану.',
    rest: 'Отдых',
    restDayMessage: 'День отдыха — восстанавливайте силы 💤',
    sets: 'подходов',
    reps: 'повторений',
    kcal: 'ккал',
    protein: 'Белки',
    carbs: 'Углеводы',
    fat: 'Жиры',
    breakfast: 'Завтрак',
    lunch: 'Обед',
    dinner: 'Ужин',
    snack: 'Перекус',
    energyLow: '🔋 Истощен',
    energyNormal: '⚡ Нормально',
    energyBeast: '🦍 Зверь',
    dayLabels: { Mon: 'Понедельник', Tue: 'Вторник', Wed: 'Среда', Thu: 'Четверг', Fri: 'Пятница', Sat: 'Суббота', Sun: 'Воскресенье' }
  }
};

export function generateNutritionHTML(mealPlans: Record<string, PlanItem[]>, today: string, weekStart: string, weekEnd: Date, language = 'en'): string {
  const tr = TRANSLATIONS[language] || TRANSLATIONS.en;
  const dayLabels = tr.dayLabels;
  const mealColors: Record<string, string> = { breakfast: '#F59E0B', lunch: '#10B981', dinner: '#7C5CFC', snack: '#3B82F6' };
  const mealEmoji: Record<string, string> = { breakfast: '🌅', lunch: '☀️', dinner: '🌙', snack: '🍎' };
  const totalCal = DAYS.reduce((a, d) => a + (mealPlans[d] || []).reduce((s, m) => s + (m.calories || 0), 0), 0);
  const totalProt = DAYS.reduce((a, d) => a + (mealPlans[d] || []).reduce((s, m) => s + (m.protein || 0), 0), 0);
  const activeDays = DAYS.filter(d => (mealPlans[d] || []).length > 0).length;
  const weStr = `${weekEnd.getFullYear()}-${String(weekEnd.getMonth() + 1).padStart(2, '0')}-${String(weekEnd.getDate()).padStart(2, '0')}`;

  const pChar = tr.protein.charAt(0);
  const cChar = tr.carbs.charAt(0);
  const fChar = tr.fat.charAt(0);

  let html = `<!DOCTYPE html><html lang="${language}"><head><meta charset="UTF-8"><title>${tr.nutritionTitle}</title><style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Inter','Helvetica Neue',sans-serif;background:#F0F4FF;color:#1E1B4B;-webkit-print-color-adjust:exact}
    .page{max-width:800px;margin:0 auto;padding:32px 24px}
    .header{background:linear-gradient(135deg,#7C5CFC 0%,#4F46E5 100%);border-radius:20px;padding:32px;margin-bottom:24px;color:white;display:flex;align-items:center;justify-content:space-between}
    .header-title{font-size:28px;font-weight:800;letter-spacing:-0.5px}
    .header-sub{font-size:14px;opacity:.85;margin-top:4px}
    .logo-badge{background:rgba(255,255,255,.2);border-radius:50%;width:64px;height:64px;display:flex;align-items:center;justify-content:center;font-size:28px}
    .summary-row{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:24px}
    .summary-card{background:white;border-radius:14px;padding:16px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}
    .summary-card .val{font-size:22px;font-weight:800;color:#7C5CFC}
    .summary-card .lbl{font-size:11px;color:#6B7280;margin-top:2px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
    .day-card{background:white;border-radius:16px;margin-bottom:20px;overflow:hidden;box-shadow:0 4px 16px rgba(0,0,0,.06);page-break-inside:avoid}
    .day-header{padding:14px 20px;display:flex;align-items:center;justify-content:space-between;background:#F9F7FF;border-bottom:1px solid #EDE9FE}
    .day-name{font-size:18px;font-weight:700;color:#4F46E5}
    .day-totals{font-size:12px;color:#6B7280;font-weight:600;background:#EDE9FE;padding:4px 10px;border-radius:20px}
    .meal-row{display:grid;grid-template-columns:100px 1fr auto;align-items:center;gap:12px;padding:14px 20px;border-bottom:1px solid #F3F4F6}
    .meal-row:last-child{border-bottom:none}
    .meal-badge{display:inline-flex;align-items:center;gap:5px;padding:4px 10px;border-radius:20px;font-size:11px;font-weight:700;text-transform:uppercase;color:white}
    .meal-name{font-size:14px;font-weight:500;color:#374151;line-height:1.4}
    .meal-macros{text-align:right}
    .meal-kcal{font-size:16px;font-weight:800;color:#7C5CFC}
    .meal-macro-row{font-size:10px;color:#9CA3AF;margin-top:2px}
    .rest-day{text-align:center;padding:24px;color:#9CA3AF;font-size:15px}
    .footer{text-align:center;margin-top:32px;font-size:11px;color:#9CA3AF}
  </style></head><body><div class="page">`;

  html += `<div class="header"><div><div class="header-title">🥗 ${tr.nutritionHeader}</div><div class="header-sub">FitGO · ${weekStart} ${tr.to} ${weStr}</div></div><div class="logo-badge">💪</div></div>`;
  html += `<div class="summary-row"><div class="summary-card"><div class="val">${activeDays}</div><div class="lbl">${tr.plannedDays}</div></div><div class="summary-card"><div class="val">${Math.round(activeDays > 0 ? totalCal / activeDays : 0)}</div><div class="lbl">${tr.kcalPerDay}</div></div><div class="summary-card"><div class="val">${Math.round(activeDays > 0 ? totalProt / activeDays : 0)}g</div><div class="lbl">${tr.proteinPerDay}</div></div></div>`;

  DAYS.forEach(day => {
    const meals = mealPlans[day] || [];
    const dl = dayLabels[day] || day;
    const dc = meals.reduce((s: number, m) => s + (m.calories || 0), 0);
    const dp = meals.reduce((s: number, m) => s + (m.protein || 0), 0);
    const dcarb = meals.reduce((s: number, m) => s + (m.carbs || 0), 0);
    const df = meals.reduce((s: number, m) => s + (m.fat || 0), 0);
    html += `<div class="day-card"><div class="day-header"><span class="day-name">${dl}</span>`;
    if (meals.length > 0) html += `<span class="day-totals">${dc} ${tr.kcal} · ${pChar}:${dp}g ${cChar}:${dcarb}g ${fChar}:${df}g</span>`;
    html += `</div>`;
    if (meals.length === 0) html += `<div class="rest-day">${tr.noMealsPlanned}</div>`;
    else meals.forEach((m: PlanItem) => {
      const c = mealColors[m.meal] || '#7C5CFC';
      const e = mealEmoji[m.meal] || '🍽️';
      const mealLabel = tr[m.meal as 'breakfast' | 'lunch' | 'dinner' | 'snack'] || m.meal;
      html += `<div class="meal-row"><div><div class="meal-badge" style="background:${c}">${e} ${mealLabel}</div></div><div class="meal-name">${m.name}</div><div class="meal-macros"><div class="meal-kcal">${m.calories}</div><div class="meal-macro-row">${pChar} ${m.protein}g · ${cChar} ${m.carbs}g · ${fChar} ${m.fat}g</div></div></div>`;
    });
    html += `</div>`;
  });

  html += `<div class="footer">${tr.generatedBy} · ${today} · ${tr.forReferenceOnly}</div></div></body></html>`;
  return html;
}

export function generateWorkoutHTML(workoutPlans: Record<string, WorkoutRoutine>, energyMode: string, today: string, weekStart: string, weekEnd: Date, language = 'en'): string {
  const tr = TRANSLATIONS[language] || TRANSLATIONS.en;
  const dayLabels = tr.dayLabels;
  const energyLabels: Record<string, string> = { low: tr.energyLow, normal: tr.energyNormal, beast: tr.energyBeast };
  const weStr = `${weekEnd.getFullYear()}-${String(weekEnd.getMonth() + 1).padStart(2, '0')}-${String(weekEnd.getDate()).padStart(2, '0')}`;
  const totalWorkoutDays = DAYS.filter(d => (workoutPlans[d]?.exercises?.length ?? 0) > 0).length;
  const totalExercises = DAYS.reduce((a, d) => a + (workoutPlans[d]?.exercises?.length ?? 0), 0);

  let html = `<!DOCTYPE html><html lang="${language}"><head><meta charset="UTF-8"><title>${tr.workoutTitle}</title><style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Inter','Helvetica Neue',sans-serif;background:#F0F4FF;color:#1E1B4B;-webkit-print-color-adjust:exact}
    .page{max-width:800px;margin:0 auto;padding:32px 24px}
    .header{background:linear-gradient(135deg,#7C5CFC 0%,#06B6D4 100%);border-radius:20px;padding:32px;margin-bottom:24px;color:white;display:flex;align-items:center;justify-content:space-between}
    .header-title{font-size:28px;font-weight:800;letter-spacing:-0.5px}
    .header-sub{font-size:14px;opacity:.85;margin-top:4px}
    .logo-badge{background:rgba(255,255,255,.2);border-radius:50%;width:64px;height:64px;display:flex;align-items:center;justify-content:center;font-size:28px}
    .summary-row{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}
    .summary-card{background:white;border-radius:14px;padding:16px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}
    .summary-card .val{font-size:22px;font-weight:800;color:#7C5CFC}
    .summary-card .lbl{font-size:11px;color:#6B7280;margin-top:2px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
    .disclaimer{background:#FEF3C7;border:1px solid #FCD34D;border-radius:12px;padding:12px 16px;margin-bottom:24px;font-size:12px;color:#92400E;display:flex;gap:8px;align-items:flex-start}
    .day-card{background:white;border-radius:16px;margin-bottom:20px;overflow:hidden;box-shadow:0 4px 16px rgba(0,0,0,.06);page-break-inside:avoid}
    .day-header{padding:14px 20px;display:flex;align-items:center;justify-content:space-between;background:#F9F7FF;border-bottom:1px solid #EDE9FE}
    .day-name{font-size:18px;font-weight:700;color:#4F46E5}
    .routine-name{font-size:12px;color:#6D28D9;font-weight:600;background:#EDE9FE;padding:4px 10px;border-radius:20px}
    .rest-badge{font-size:12px;color:#6B7280;background:#F3F4F6;padding:4px 10px;border-radius:20px;font-weight:600}
    .ex-row{display:grid;grid-template-columns:1fr auto;align-items:center;gap:12px;padding:14px 20px;border-bottom:1px solid #F3F4F6}
    .ex-row:last-child{border-bottom:none}
    .ex-num{font-size:11px;font-weight:800;color:#9CA3AF;margin-bottom:3px}
    .ex-name{font-size:15px;font-weight:600;color:#1E1B4B}
    .badge{padding:4px 10px;border-radius:8px;font-size:12px;font-weight:700}
    .badge-sets{background:#EDE9FE;color:#6D28D9}
    .badge-reps{background:#DCFCE7;color:#166534}
    .badge-rest{background:#FEF3C7;color:#92400E}
    .rest-day{text-align:center;padding:28px;color:#9CA3AF;font-size:15px}
    .footer{text-align:center;margin-top:32px;font-size:11px;color:#9CA3AF}
  </style></head><body><div class="page">`;

  html += `<div class="header"><div><div class="header-title">🏋️ ${tr.workoutHeader}</div><div class="header-sub">FitGO · ${weekStart} ${tr.to} ${weStr}</div></div><div class="logo-badge">🔥</div></div>`;
  html += `<div class="summary-row"><div class="summary-card"><div class="val">${totalWorkoutDays}</div><div class="lbl">${tr.workoutDays}</div></div><div class="summary-card"><div class="val">${totalExercises}</div><div class="lbl">${tr.totalExercises}</div></div><div class="summary-card"><div class="val">${energyLabels[energyMode] || energyLabels.normal}</div><div class="lbl">${tr.energy}</div></div></div>`;
  html += `<div class="disclaimer"><span>⚠️</span><span>${tr.disclaimer}</span></div>`;

  DAYS.forEach(day => {
    const w = workoutPlans[day];
    const dl = dayLabels[day] || day;
    const isRest = !w || (w.exercises?.length ?? 0) === 0;
    html += `<div class="day-card"><div class="day-header"><span class="day-name">${dl}</span>`;
    if (isRest) html += `<span class="rest-badge">😴 ${tr.rest}</span>`;
    else html += `<span class="routine-name">${w!.name}</span>`;
    html += `</div>`;
    if (isRest) html += `<div class="rest-day">${tr.restDayMessage}</div>`;
    else w!.exercises.forEach((ex: any, i: number) => {
      html += `<div class="ex-row"><div><div class="ex-num">#${i + 1}</div><div class="ex-name">${ex.name}</div></div><span class="badge badge-sets">${ex.sets} ${tr.sets}</span><span class="badge badge-reps">${ex.reps} ${tr.reps}</span><span class="badge badge-rest">⏱ ${ex.rest}</span></div>`;
    });
    html += `</div>`;
  });

  html += `<div class="footer">${tr.generatedBy} · ${today} · ${tr.forReferenceOnly}</div></div></body></html>`;
  return html;
}
