import {
  Sparkles, Send, Camera, Mic, Clock,
  MessageSquarePlus, Apple, Salad, Flame,
  BarChart2, Edit2, ShieldAlert, Heart, Compass, Zap, Activity, Dumbbell
} from 'lucide-react-native';

export const COACH_CONFIG = {
  trainer: {
    type: 'trainer' as const,
    messagesKey: 'trainerMessages' as const,
    sessionsKey: 'trainerSessions' as const,
    sessionIdKey: 'currentTrainerSessionId' as const,
    badgeImage: require('../assets/trainer_badge.jpg'),
    headerLabel: 'coach.trainer.label',
    headerLabelDefault: 'Personal Trainer',
    tag: '[TrainerScreen]',
    hasAnimatedPulse: true,
    useParamPrompt: true,
    defaultSuggestions: [
      { icon: Flame, color: '#EF4444' },
      { icon: Dumbbell, color: '#8B5CF6' },
      { icon: Zap, color: '#F59E0B' },
      { icon: Compass, color: '#10B981' },
    ],
    suggestionCardPadding: 14,
    suggestionCardMinHeight: 115,
    suggestionIconSize: 32,
    suggestionCardFontSize: 13,
    suggestionCardLineHeight: 18,
  },
  doctor: {
    type: 'doctor' as const,
    messagesKey: 'doctorMessages' as const,
    sessionsKey: 'doctorSessions' as const,
    sessionIdKey: 'currentDoctorSessionId' as const,
    badgeImage: require('../assets/doctor_badge.jpg'),
    headerLabel: 'coach.doctor.label',
    headerLabelDefault: 'Personal Doctor',
    tag: '[DoctorScreen]',
    hasAnimatedPulse: false,
    useParamPrompt: false,
    defaultSuggestions: [
      { icon: Clock, color: '#3B82F6' },
      { icon: Activity, color: '#EF4444' },
      { icon: Sparkles, color: '#8B5CF6' },
      { icon: Heart, color: '#10B981' },
    ],
    suggestionCardPadding: 14,
    suggestionCardMinHeight: 115,
    suggestionIconSize: 32,
    suggestionCardFontSize: 13,
    suggestionCardLineHeight: 18,
  },
  nutritionist: {
    type: 'nutritionist' as const,
    messagesKey: 'nutritionistMessages' as const,
    sessionsKey: 'nutritionistSessions' as const,
    sessionIdKey: 'currentNutritionistSessionId' as const,
    badgeImage: require('../assets/nutritionist_badge.jpg'),
    headerLabel: 'coach.nutritionist.label',
    headerLabelDefault: 'Nutritionist',
    tag: '[NutritionistScreen]',
    hasAnimatedPulse: false,
    useParamPrompt: true,
    defaultSuggestions: [
      { icon: Apple, color: '#10B981' },
      { icon: Salad, color: '#34D399' },
      { icon: Flame, color: '#EF4444' },
      { icon: BarChart2, color: '#3B82F6' },
    ],
    suggestionCardPadding: 12,
    suggestionCardMinHeight: 90,
    suggestionIconSize: 28,
    suggestionCardFontSize: 12,
    suggestionCardLineHeight: 16,
  },
};

export type CoachType = keyof typeof COACH_CONFIG;
