import {
  Flame, Dumbbell, Heart, Activity, Zap, Compass, Clock, Sparkles, Apple, Salad, BarChart2
} from 'lucide-react-native';

export const COACH_CONFIG = {
  trainer: {
    type: 'trainer' as const,
    messagesKey: 'trainerMessages' as const,
    sessionsKey: 'trainerSessions' as const,
    sessionIdKey: 'currentTrainerSessionId' as const,
    badgeImage: require('../assets/trainer_badge.jpg'),
    headerLabel: 'coach.trainer.label',
    headerLabelDefault: 'Coach de Entrenamiento',
    subtitleKey: 'coach.trainer.subtitle',
    subtitle: 'Tu entrenador personal IA',
    heroGreetingKey: 'coach.trainer.heroGreeting',
    heroGreeting: 'Soy tu Coach de Entrenamiento. Estoy aquí para diseñar tus rutinas, mejorar tu técnica y maximizar tus resultados.',
    heroQuestionKey: 'coach.trainer.heroQuestion',
    heroQuestion: '¿Qué quieres entrenar hoy?',
    tag: '[TrainerScreen]',
    hasAnimatedPulse: true,
    useParamPrompt: true,
    quickActions: [
      {
        id: 'routine',
        titleKey: 'coach.trainer.quickActions.routine.title',
        title: 'Crear rutina de hoy',
        subtitleKey: 'coach.trainer.quickActions.routine.subtitle',
        subtitle: 'Diseña tu sesión según tu tiempo y equipo.',
        icon: Dumbbell,
        color: '#8B5CF6',
        promptKey: 'coach.trainer.quickActions.routine.prompt',
        prompt: 'Diseña una rutina efectiva de entrenamiento para hoy basada en mi nivel, tiempo disponible y objetivo 💪',
      },
      {
        id: 'warmup',
        titleKey: 'coach.trainer.quickActions.warmup.title',
        title: 'Calentamiento exprés',
        subtitleKey: 'coach.trainer.quickActions.warmup.subtitle',
        subtitle: 'Actívate en 5-10 minutos sin lesiones.',
        icon: Flame,
        color: '#EF4444',
        promptKey: 'coach.trainer.quickActions.warmup.prompt',
        prompt: 'Dame una rutina de calentamiento dinámico y movilidad articular de 8 minutos antes de entrenar 🔥',
      },
      {
        id: 'technique',
        titleKey: 'coach.trainer.quickActions.technique.title',
        title: 'Corregir mi técnica',
        subtitleKey: 'coach.trainer.quickActions.technique.subtitle',
        subtitle: 'Postura, rango y errores comunes.',
        icon: Activity,
        color: '#10B981',
        promptKey: 'coach.trainer.quickActions.technique.prompt',
        prompt: '¿Cuáles son las claves posturales y errores más comunes en sentadilla, press de banca y peso muerto?',
      },
      {
        id: 'adapt',
        titleKey: 'coach.trainer.quickActions.adapt.title',
        title: 'Adaptar por molestia',
        subtitleKey: 'coach.trainer.quickActions.adapt.subtitle',
        subtitle: 'Variantes seguras si sientes dolor o fatiga.',
        icon: Compass,
        color: '#3B82F6',
        promptKey: 'coach.trainer.quickActions.adapt.prompt',
        prompt: '¿Qué ejercicios alternativos puedo hacer si siento molestias en las rodillas o en los hombros?',
      },
    ],
    defaultSuggestions: [
      { icon: Flame, color: '#EF4444' },
      { icon: Dumbbell, color: '#8B5CF6' },
      { icon: Zap, color: '#F59E0B' },
      { icon: Compass, color: '#10B981' },
    ],
    suggestionCardPadding: 14,
    suggestionCardMinHeight: 115,
    suggestionIconSize: 32,
    suggestionCardFontSize: 13,
    suggestionCardLineHeight: 18,
  },
  doctor: {
    type: 'doctor' as const,
    messagesKey: 'doctorMessages' as const,
    sessionsKey: 'doctorSessions' as const,
    sessionIdKey: 'currentDoctorSessionId' as const,
    badgeImage: require('../assets/doctor_badge.jpg'),
    headerLabel: 'coach.doctor.label',
    headerLabelDefault: 'Coach de Bienestar',
    subtitleKey: 'coach.doctor.subtitle',
    subtitle: 'Tu asesor de salud y recuperación IA',
    heroGreetingKey: 'coach.doctor.heroGreeting',
    heroGreeting: 'Soy tu Coach de Bienestar. Estoy aquí para cuidar tu recuperación muscular, sueño, hábitos y salud integral.',
    heroQuestionKey: 'coach.doctor.heroQuestion',
    heroQuestion: '¿Cómo te sientes hoy?',
    tag: '[DoctorScreen]',
    hasAnimatedPulse: false,
    useParamPrompt: false,
    quickActions: [
      {
        id: 'sleep',
        titleKey: 'coach.doctor.quickActions.sleep.title',
        title: 'Mejorar mi descanso',
        subtitleKey: 'coach.doctor.quickActions.sleep.subtitle',
        subtitle: 'Pautas para dormir profundo y regenerar.',
        icon: Clock,
        color: '#6366F1',
        promptKey: 'coach.doctor.quickActions.sleep.prompt',
        prompt: '¿Cómo puedo optimizar mi higiene de sueño para despertar con más energía y acelerar mi recuperación? 🛌',
      },
      {
        id: 'fatigue',
        titleKey: 'coach.doctor.quickActions.fatigue.title',
        title: 'Combatir la fatiga',
        subtitleKey: 'coach.doctor.quickActions.fatigue.subtitle',
        subtitle: 'Energía sostenida y menos cansancio.',
        icon: Zap,
        color: '#F59E0B',
        promptKey: 'coach.doctor.quickActions.fatigue.prompt',
        prompt: '¿Por qué me siento con baja energía o fatiga durante el día y qué cambios simples puedo aplicar? ⚡',
      },
      {
        id: 'supplements',
        titleKey: 'coach.doctor.quickActions.supplements.title',
        title: 'Suplementos recomendados',
        subtitleKey: 'coach.doctor.quickActions.supplements.subtitle',
        subtitle: 'Evidencia científica y cómo tomarlos.',
        icon: Sparkles,
        color: '#8B5CF6',
        promptKey: 'coach.doctor.quickActions.supplements.prompt',
        prompt: '¿Qué suplementos tienen mayor evidencia científica para mi objetivo y cómo debería tomarlos? 💊',
      },
      {
        id: 'recovery',
        titleKey: 'coach.doctor.quickActions.recovery.title',
        title: 'Recuperación activa',
        subtitleKey: 'coach.doctor.quickActions.recovery.subtitle',
        subtitle: 'Alivio de agujetas y descanso activo.',
        icon: Heart,
        color: '#10B981',
        promptKey: 'coach.doctor.quickActions.recovery.prompt',
        prompt: '¿Cuáles son las mejores estrategias de recuperación activa para aliviar el dolor muscular y las agujetas? 🧘',
      },
    ],
    defaultSuggestions: [
      { icon: Clock, color: '#3B82F6' },
      { icon: Activity, color: '#EF4444' },
      { icon: Sparkles, color: '#8B5CF6' },
      { icon: Heart, color: '#10B981' },
    ],
    suggestionCardPadding: 14,
    suggestionCardMinHeight: 115,
    suggestionIconSize: 32,
    suggestionCardFontSize: 13,
    suggestionCardLineHeight: 18,
  },
  nutritionist: {
    type: 'nutritionist' as const,
    messagesKey: 'nutritionistMessages' as const,
    sessionsKey: 'nutritionistSessions' as const,
    sessionIdKey: 'currentNutritionistSessionId' as const,
    badgeImage: require('../assets/nutritionist_badge.jpg'),
    headerLabel: 'coach.nutritionist.label',
    headerLabelDefault: 'Coach de Alimentación',
    subtitleKey: 'coach.nutritionist.subtitle',
    subtitle: 'Tu asistente nutricional IA',
    heroGreetingKey: 'coach.nutritionist.heroGreeting',
    heroGreeting: 'Soy tu Coach de Alimentación. Estoy aquí para ayudarte a tomar mejores decisiones con tu dieta y alcanzar tus metas.',
    heroQuestionKey: 'coach.nutritionist.heroQuestion',
    heroQuestion: '¿Qué quieres hacer hoy?',
    tag: '[NutritionistScreen]',
    hasAnimatedPulse: false,
    useParamPrompt: true,
    quickActions: [
      {
        id: 'plan_meal',
        titleKey: 'coach.nutritionist.quickActions.plan_meal.title',
        title: 'Planear una comida',
        subtitleKey: 'coach.nutritionist.quickActions.plan_meal.subtitle',
        subtitle: 'Recetas y opciones según tus objetivos.',
        icon: Apple,
        color: '#8B5CF6',
        promptKey: 'coach.nutritionist.quickActions.plan_meal.prompt',
        prompt: '¿Puedes planear una comida balanceada y alta en proteína ajustada a mis requerimientos diarios?',
      },
      {
        id: 'choose_snack',
        titleKey: 'coach.nutritionist.quickActions.choose_snack.title',
        title: 'Elegir un snack',
        subtitleKey: 'coach.nutritionist.quickActions.choose_snack.subtitle',
        subtitle: 'Opciones saludables y que te llenan.',
        icon: Salad,
        color: '#10B981',
        promptKey: 'coach.nutritionist.quickActions.choose_snack.prompt',
        prompt: '¿Qué snacks saludables, rápidos y saciantes me recomiendas para comer entre comidas?',
      },
      {
        id: 'calc_protein',
        titleKey: 'coach.nutritionist.quickActions.calc_protein.title',
        title: 'Calcular mi proteína',
        subtitleKey: 'coach.nutritionist.quickActions.calc_protein.subtitle',
        subtitle: '¿Cuánta necesitas según tu objetivo?',
        icon: Dumbbell,
        color: '#3B82F6',
        promptKey: 'coach.nutritionist.quickActions.calc_protein.prompt',
        prompt: '¿Cuánta proteína debo comer al día según mi peso y objetivo, y cómo distribuirla en mis comidas? 🥩',
      },
      {
        id: 'analyze_diet',
        titleKey: 'coach.nutritionist.quickActions.analyze_diet.title',
        title: 'Analizar mi dieta',
        subtitleKey: 'coach.nutritionist.quickActions.analyze_diet.subtitle',
        subtitle: 'Revisa tu progreso y recibe recomendaciones.',
        icon: BarChart2,
        color: '#F59E0B',
        promptKey: 'coach.nutritionist.quickActions.analyze_diet.prompt',
        prompt: 'Analiza lo que llevo consumido hoy según mis registros y dame sugerencias prácticas para mejorar mi dieta 📊',
      },
    ],
    defaultSuggestions: [
      { icon: Apple, color: '#10B981' },
      { icon: Salad, color: '#34D399' },
      { icon: Flame, color: '#EF4444' },
      { icon: BarChart2, color: '#3B82F6' },
    ],
    suggestionCardPadding: 12,
    suggestionCardMinHeight: 90,
    suggestionIconSize: 28,
    suggestionCardFontSize: 12,
    suggestionCardLineHeight: 16,
  },
};

export type CoachType = keyof typeof COACH_CONFIG;
