-- Abre el SQL Editor en tu panel de Supabase y ejecuta esto:

UPDATE public.users
SET 
  unlocked_achievements = ARRAY[
    'welcome', 'premium_club', 'dark_mode_lover', 'profile_complete', 'streak_3', 'streak_7', 'streak_30', 'streak_100', 'streak_365', 'streak_500', 'streak_1000', 'first_log', 'early_bird', 'protein_goal', 'healthy_eater', 'perfect_macros', 'water_habit', 'water_champion', 'water_god', 'water_ocean', 'diet_expert', 'hydration_streak_7', 'nutrition_scholar', 'carnival_eater', 'vegan_day', 'protein_pancake', 'late_snack', 'perfect_week_macros', 'carnivore', 'sweet_tooth', 'coffee_addict', 'fasting_monk', 'chef_kiss', 'goal_reached', 'weight_loss_1', 'muscle_gain_1', 'weight_loss_10', 'muscle_gain_10', 'body_sculptor', 'photo_pioneer', 'step_master', 'step_marathon', 'step_half_marathon', 'workout_warrior', 'workout_machine', 'sleep_master', 'sleep_champion', 'sleep_god', 'social_star', 'social_influence', 'friend_magnet', 'community_pillar', 'beta_tester', 'developer_god', 'the_owner', 'bug_hunter', 'night_owl', 'easter_egg_hunter', 'ghost_mode', 'matrix_glitch', 'time_traveler', 'heavy_lifter', 'flash_speed', 'zen_mode', 'iron_lungs', 'mountain_climber', 'viral_post', 'first_comment', 'helper', 'profile_stalker', 'fitgo_veteran', 'data_nerd', 'fast_logger', 'first_like', 'like_bomber', 'squad_creator', 'squad_champion', 'trend_setter', 'chatty', 'early_lifter', 'leg_day_survivor', 'cardio_bunny', 'rest_day_respect', 'yoga_streak', '100k_steps_week', 'waist_shredder', 'biceps_pump', 'scale_fearless', 'first_compliment', 'bmi_normal', 'body_fat_15', 'spartan_300', 'kryptonian', 'goggins_mode', 'body_alchemist', 'mr_olympia', 'the_one_percent', 'iron_monk', 'immortal', 'perfect_machine', 'triceratops', 'supernova', 'god_of_war', 'holy_grail', 'five_meals', 'balanced_day', 'smoothie_lover', 'three_workouts_week', 'bike_rider', 'ten_workouts', 'fifty_workouts', 'weight_loss_5', 'muscle_gain_5', 'five_measurements', 'language_switcher', 'night_mode', 'first_week_user', 'sleep_week', 'power_nap', 'first_friend', 'three_friends'
  ],
  badges = ARRAY[
    'super_admin', 'admin', 'pro', 'beast_mode', 'verified', 'owner', 'early_adopter', 'fitness_enthusiast', 'water_champion', 'sleep_legend', 'protein_boss', 'streak_master', 'step_hero', 'weight_master', 'social_star', 'macro_expert', 'workout_warrior', 'body_sculptor', 'photo_pioneer', 'century_club', 'year_of_fitness', 'half_marathoner', 'weight_transformer', 'hydration_god', 'friend_magnet', 'community_pillar', 'workout_machine', 'sleep_god', 'early_bird', 'diet_expert', 'night_owl', 'zen_master', 'iron_lungs', 'mountain_king', 'spartan', 'data_scientist', 'ghost', 'carnivore', 'zen_streaker', 'speed_demon', 'love_reactor', 'legend_commenter'
  ],
  role = 'owner'
WHERE name ILIKE '%Elubiz%Dev%';
