import i18n from '../../i18n';
import { getLang, fetchGroq, CHAT_MODEL, FAST_MODEL } from './core';

// ─── Generate weekly meal plan ─────────────────────────────────────────────────
export async function generateMealPlan(userProfile: {
  targetCalories: number;
  macros: { protein: number; carbs: number; fat: number };
  goal: string;
  availableFoods?: string[];
  preferences?: string[];
  age?: number;
  weight?: number;
  height?: number;
  sex?: 'male' | 'female' | 'other';
  activityLevel?: string;
  dietaryRestrictions?: string[];
  medicalConditions?: string[];
  medicationsSupplements?: string[];
  tdee?: number;
}, language: string = 'en'): Promise<Record<string, { meal: string; name: string; calories: number; protein: number; carbs: number; fat: number }[]>> {
  const targetLang = getLang(language);

  // Build a human-readable goal context
  const goalContext = userProfile.goal === 'lose'
    ? 'fat loss / caloric deficit (goal: lose body fat while preserving muscle)'
    : userProfile.goal === 'gain'
    ? 'muscle gain / caloric surplus (goal: build lean muscle mass)'
    : 'body recomposition / weight maintenance (goal: maintain weight and improve body composition)';

  // Determine activity level description
  const activityDesc: Record<string, string> = {
    sedentary: 'sedentary (little or no exercise)',
    light: 'lightly active (1-3 days/week exercise)',
    moderate: 'moderately active (3-5 days/week exercise)',
    active: 'very active (6-7 days/week exercise)',
    very_active: 'extra active (hard training + physical job)',
  };
  const activityLabel = activityDesc[userProfile.activityLevel ?? ''] ?? userProfile.activityLevel ?? 'Unknown';

  // Available foods instructions
  const hasFoods = (userProfile.availableFoods?.length ?? 0) > 0;
  const foodsInstruction = hasFoods
    ? `AVAILABLE FOODS (STRICT): The user has specified these foods as available at home or preferred. You MUST build every meal using ONLY ingredients from this list or simple pantry staples (salt, oil, water, basic spices). Do NOT suggest foods outside this list: ${userProfile.availableFoods!.join(', ')}`
    : 'No specific food list provided — use a varied, balanced selection of healthy whole foods appropriate for the user\'s goal and restrictions.';

  const prompt = `You are an expert sports nutritionist and dietitian AI. Create a 7-day personalized meal plan for the following user. Your goal is maximum personalization and caloric precision.

=== USER PROFILE ===
- Name/ID: User
- Age: ${userProfile.age ?? 'Unknown'} years
- Sex: ${userProfile.sex ?? 'Unknown'}
- Weight: ${userProfile.weight ?? 'Unknown'} kg
- Height: ${userProfile.height ?? 'Unknown'} cm
- Activity Level: ${activityLabel}
- TDEE (Total Daily Energy Expenditure): ${userProfile.tdee ?? userProfile.targetCalories} kcal/day
- DAILY CALORIE TARGET: ${userProfile.targetCalories} kcal (CRITICAL — every day's total must be within ±50 kcal of this value)
- MACRO TARGETS: Protein ${userProfile.macros.protein}g | Carbs ${userProfile.macros.carbs}g | Fat ${userProfile.macros.fat}g
- Goal: ${goalContext}
- Diet Preference: ${userProfile.preferences?.[0] ?? 'Balanced'}
- Dietary Restrictions: ${userProfile.dietaryRestrictions?.filter(r => r !== 'none').join(', ') || 'None'}
- Medical Conditions: ${userProfile.medicalConditions?.filter(c => c !== 'none').join(', ') || 'None'}
- Medications/Supplements: ${userProfile.medicationsSupplements?.filter(m => m !== 'none').join(', ') || 'None'}

=== FOOD AVAILABILITY ===
${foodsInstruction}

=== CRITICAL RULES ===
1. CALORIE ACCURACY: Each day's calorie total MUST hit exactly ${userProfile.targetCalories} kcal (±50 kcal). If the user needs >3000 kcal, include larger portions AND extra snacks. Never leave a large gap.
2. MACRO ACCURACY: Match protein/carbs/fat targets as closely as possible each day.
3. MEAL STRUCTURE: Use appropriate meal count based on calories. For <2000 kcal: 3 meals. For 2000-2800 kcal: 3 meals + 1 snack. For >2800 kcal: 3 meals + 2 snacks.
4. GOAL ALIGNMENT:
   - If goal is 'lose': use high-protein, low-glycemic foods, control portions strictly.
   - If goal is 'gain': include calorie-dense foods, adequate carbs, enough protein for muscle synthesis.
   - If goal is 'maintain': balanced approach, variety.
5. MEAL PROPERTY: The "meal" JSON field MUST ALWAYS be one of these exact English strings: "breakfast", "lunch", "dinner", "snack". NEVER translate this.
6. LANGUAGE: All "name" fields and the "warning" text MUST be written in ${targetLang}.
7. MEDICAL SAFETY: If the user has medical conditions, adapt the diet accordingly (e.g., diabetics: limit simple carbs; hypertension: limit sodium). Always note this in the warning.
8. DISCLAIMER: You MUST include a "warning" field with a clear disclaimer in ${targetLang} stating: (a) this plan is generated by an AI and is not a substitute for professional medical or nutritional advice, (b) the user should consult a registered dietitian or physician before starting, especially if they have medical conditions or take medications.
9. VARIETY: Do not repeat the same meal more than 2 times across the 7-day plan. Use diverse, realistic, and practical meal ideas.
10. PORTION SPECIFICITY: Always include realistic portion descriptions in the meal name (e.g., "150g grilled chicken breast with 200g brown rice and salad").

Return ONLY a single, valid, complete JSON object.
CRITICAL FORMAT RULES:
- Do NOT output markdown code fences (such as \`\`\`json).
- Do NOT include reasoning, commentary, or text before or after the JSON.
- Output MUST start with '{' and end with '}'.
- Every single day ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun") MUST contain a complete array of meal objects.
- NEVER use ellipsis (...) or placeholder syntax like [...] in any property or array.

JSON Schema format (must include all 7 days: Mon, Tue, Wed, Thu, Fri, Sat, Sun):
{
  "warning": "Disclaimer in ${targetLang}",
  "Mon": [
    { "meal": "breakfast", "name": "Meal name and portion in ${targetLang}", "calories": 500, "protein": 35, "carbs": 55, "fat": 15 },
    { "meal": "lunch", "name": "Meal name and portion in ${targetLang}", "calories": 700, "protein": 50, "carbs": 80, "fat": 20 },
    { "meal": "dinner", "name": "Meal name and portion in ${targetLang}", "calories": 600, "protein": 45, "carbs": 70, "fat": 18 },
    { "meal": "snack", "name": "Snack name and portion in ${targetLang}", "calories": 200, "protein": 20, "carbs": 25, "fat": 8 }
  ],
  "Tue": [ ...same 3-4 meal objects... ],
  "Wed": [ ...same 3-4 meal objects... ],
  "Thu": [ ...same 3-4 meal objects... ],
  "Fri": [ ...same 3-4 meal objects... ],
  "Sat": [ ...same 3-4 meal objects... ],
  "Sun": [ ...same 3-4 meal objects... ]
}`;

  const data = await fetchGroq({
    model: CHAT_MODEL,
    messages: [
      {
        role: 'system',
        content: 'You are an expert sports nutritionist and dietitian AI. You must respond ONLY with a raw valid JSON object matching the requested schema. Never include markdown formatting (such as ```json), thinking tags, or conversational text.'
      },
      { role: 'user', content: prompt }
    ],
    max_tokens: 8192,
    temperature: 0.2,
    response_format: { type: 'json_object' },
  });

  let text = (data.choices[0]?.message?.content ?? '').trim();
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  text = text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();

  let parsed: any;
  try {
    parsed = JSON.parse(text);
  } catch {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start !== -1 && end > start) {
      try {
        parsed = JSON.parse(text.slice(start, end + 1));
      } catch {
        throw new Error('Failed to parse meal plan from AI. Please try again.');
      }
    } else {
      throw new Error('Failed to parse meal plan from AI. Please try again.');
    }
  }

  // Validate that all 7 days are present — a truncated response (due to token limit)
  // will be missing Sat/Sun which causes the "only breakfast on Saturday, empty Sunday" bug.
  const requiredDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const missingDays = requiredDays.filter(d => !parsed[d] || !Array.isArray(parsed[d]) || parsed[d].length === 0);
  if (missingDays.length > 0) {
    throw new Error(i18n.t('groq.incompletePlan', { days: missingDays.join(', ') }));
  }

  return parsed;
}

export async function generateDailyMealPlan(userProfile: any, language: string = 'en', day: string): Promise<any> {
  const targetLang = getLang(language);
  const goalContext = userProfile.goal === 'lose'
    ? 'fat loss / caloric deficit'
    : userProfile.goal === 'gain'
    ? 'muscle gain / caloric surplus'
    : 'body recomposition / weight maintenance';

  const activityDesc: Record<string, string> = {
    sedentary: 'sedentary (little or no exercise)',
    light: 'lightly active (1-3 days/week exercise)',
    moderate: 'moderately active (3-5 days/week exercise)',
    active: 'very active (6-7 days/week exercise)',
    very_active: 'extra active (hard training + physical job)',
  };
  const activityLabel = activityDesc[userProfile.activityLevel ?? ''] ?? userProfile.activityLevel ?? 'Unknown';

  const hasFoods = (userProfile.availableFoods?.length ?? 0) > 0;
  const foodsInstruction = hasFoods
    ? `AVAILABLE FOODS (STRICT): You MUST build every meal using ONLY ingredients from this list: ${userProfile.availableFoods!.join(', ')}`
    : 'No specific food list provided.';

  const targetCal = userProfile.targetCalories || 2000;
  const macros = userProfile.macros || { protein: 150, carbs: 250, fat: 65 };

  const prompt = `You are an expert sports nutritionist AI. Create a 1-day personalized meal plan for the user for the day: ${day}.
=== USER PROFILE ===
- Goal: ${goalContext}
- Target Calories: ${targetCal} kcal (Must hit EXACTLY ±50 kcal)
- Macro Targets: Protein ${macros.protein}g | Carbs ${macros.carbs}g | Fat ${macros.fat}g
- Activity Level: ${activityLabel}
- Diet Preference: ${userProfile.preferences?.[0] ?? 'Balanced'}
- Restrictions: ${userProfile.dietaryRestrictions?.filter((r:string) => r !== 'none').join(', ') || 'None'}
- Medical Conditions: ${userProfile.medicalConditions?.filter((c:string) => c !== 'none').join(', ') || 'None'}
=== FOOD AVAILABILITY ===
${foodsInstruction}

Return ONLY a valid JSON object starting with '{' and ending with '}':
{
  "${day}": [
    { "meal": "breakfast", "name": "Meal name and portion in ${targetLang}", "calories": 500, "protein": 35, "carbs": 55, "fat": 15 },
    { "meal": "lunch", "name": "Meal name and portion in ${targetLang}", "calories": 700, "protein": 50, "carbs": 80, "fat": 20 },
    { "meal": "dinner", "name": "Meal name and portion in ${targetLang}", "calories": 600, "protein": 45, "carbs": 70, "fat": 18 },
    { "meal": "snack", "name": "Snack name and portion in ${targetLang}", "calories": 200, "protein": 20, "carbs": 25, "fat": 8 }
  ]
}`;

  const data = await fetchGroq({
    model: CHAT_MODEL,
    messages: [
      {
        role: 'system',
        content: 'You are an expert sports nutritionist AI. You must respond ONLY with a raw valid JSON object matching the requested schema. Never output markdown code blocks or thinking tags.'
      },
      { role: 'user', content: prompt }
    ],
    max_tokens: 2048,
    temperature: 0.2,
    response_format: { type: 'json_object' },
  });

  let text = (data.choices[0]?.message?.content ?? '').trim();
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  text = text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
  try {
    return JSON.parse(text);
  } catch {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start !== -1 && end > start) {
      try {
        return JSON.parse(text.slice(start, end + 1));
      } catch {
        throw new Error('Failed to parse daily meal plan from AI. Please try again.');
      }
    }
    throw new Error('Failed to parse daily meal plan from AI. Please try again.');
  }
}

// ─── Swap Meal ───────────────────────────────────────────────────────────────
export async function generateMealSwap(name: string, cal: number, protein: number, carbs: number, fat: number, profile: any, language: string = 'en'): Promise<any> {
  const targetLang = getLang(language);
  const prompt = `You are an expert nutritionist. The user wants to replace their meal "${name}" (${cal} kcal, ${protein}g protein, ${carbs}g carbs, ${fat}g fat).
Provide a DIFFERENT healthy meal alternative with the EXACT same macros (+/- 5%).
Dietary restrictions: ${profile?.dietaryRestrictions?.join(', ') || 'None'}
IMPORTANT: The "name" field MUST be a non-empty string written in ${targetLang}.
Return ONLY a valid JSON object:
{
  "name": "Descriptive meal name in ${targetLang} (required, must not be empty)",
  "calories": ${cal},
  "protein": ${protein},
  "carbs": ${carbs},
  "fat": ${fat}
}`;

  try {
    const data = await fetchGroq({
      model: FAST_MODEL,
      messages: [
        {
          role: 'system',
          content: 'You are an expert nutritionist AI. You must respond ONLY with a valid JSON object.'
        },
        { role: 'user', content: prompt }
      ],
      max_tokens: 500,
      temperature: 0.7,
      response_format: { type: 'json_object' },
    });
    let text = (data.choices[0]?.message?.content ?? '').trim();
    const startIndex = text.indexOf('{');
    const endIndex = text.lastIndexOf('}');
    if (startIndex !== -1 && endIndex !== -1) {
      text = text.slice(startIndex, endIndex + 1);
    }
    return JSON.parse(text);
  } catch (error) {
    console.error('Error in generateMealSwap:', error);
    throw error;
  }
}
