import { StyleSheet } from 'react-native';

export const STEPS = [
  'goal', 'stats', 'activity', 'lifestyle',
  'dietaryRestrictions', 'medicalConditions', 'medications',
  'dietType', 'diet', 'personalization', 'terms', 'projection'
] as const;

export type Step = typeof STEPS[number];

export interface OnboardingData {
  goal:         'lose' | 'maintain' | 'gain';
  sex:          'male' | 'female' | 'other';
  customGender?: string;
  age:          number;
  weight:       number;
  height:       number;
  activityLevel:'sedentary'|'light'|'moderate'|'active'|'very_active';
  lifestyle:     'seated'|'standing_sometimes'|'standing_mostly'|'moving'|'physical_work';
  dietaryRestrictions: string[];
  medicalConditions: string[];
  medicationsSupplements: string[];
  dietType:     'recommended' | 'high_protein' | 'low_carb' | 'keto' | 'low_fat';
  targetWeight: number;
  velocity:     'slow' | 'moderate' | 'fast';
  availableFoods: string[];
  weightUnit:   'kg' | 'lbs';
  heightUnit:   'cm' | 'ft';
  termsAccepted?: boolean;
}

export interface StepProps {
  value: Partial<OnboardingData>;
  onChange: (d: Partial<OnboardingData>) => void;
  colors?: any;
  t?: any;
  profile?: any;
}

export const FOOD_CATEGORIES = [
  {
    id: 'proteins', title: 'proteins', min: 3,
    items: [
      { id: 'chicken', label: 'chicken', emoji: '🍗' },
      { id: 'beef', label: 'beef', emoji: '🥩' },
      { id: 'fish', label: 'fish', emoji: '🐟' },
      { id: 'pork', label: 'pork', emoji: '🍖' },
      { id: 'eggs', label: 'eggs', emoji: '🥚' },
      { id: 'turkey', label: 'turkey', emoji: '🦃' },
      { id: 'tuna', label: 'tuna', emoji: '🐠' },
      { id: 'salmon', label: 'salmon', emoji: '🍣' },
      { id: 'shrimp', label: 'shrimp', emoji: '🦐' },
      { id: 'tilapia', label: 'tilapia', emoji: '🐟' },
      { id: 'octopus', label: 'octopus', emoji: '🐙' },
      { id: 'squid', label: 'squid', emoji: '🦑' },
      { id: 'crab', label: 'crab', emoji: '🦀' },
      { id: 'sardines', label: 'sardines', emoji: '🐟' },
      { id: 'lamb', label: 'lamb', emoji: '🍖' },
      { id: 'goat', label: 'goat', emoji: '🥩' },
      { id: 'duck', label: 'duck', emoji: '🦆' },
      { id: 'rabbit', label: 'rabbit', emoji: '🐇' },
      { id: 'guinea_pig', label: 'guinea_pig', emoji: '🥩' },
      { id: 'chorizo', label: 'chorizo', emoji: '🌭' },
      { id: 'morcilla', label: 'morcilla', emoji: '🥩' },
      { id: 'chicharron', label: 'chicharron', emoji: '🥓' },
      { id: 'cecina', label: 'cecina', emoji: '🥩' },
      { id: 'tofu', label: 'tofu', emoji: '🍱' },
      { id: 'tempeh', label: 'tempeh', emoji: '🌱' },
      { id: 'seitan', label: 'seitan', emoji: '🌾' },
      { id: 'protein_powder', label: 'protein_powder', emoji: '💪' },
      { id: 'greek_yogurt', label: 'greek_yogurt', emoji: '🥄' },
      { id: 'cottage_cheese', label: 'cottage_cheese', emoji: '🧀' },
      { id: 'quail_eggs', label: 'quail_eggs', emoji: '🥚' }
    ]
  },
  {
    id: 'carbs', title: 'carbs', min: 3,
    items: [
      { id: 'rice', label: 'rice', emoji: '🍚' },
      { id: 'potato', label: 'potato', emoji: '🥔' },
      { id: 'sweet_potato', label: 'sweet_potato', emoji: '🍠' },
      { id: 'cassava', label: 'cassava', emoji: '🥔' },
      { id: 'corn', label: 'corn', emoji: '🌽' },
      { id: 'plantain', label: 'plantain', emoji: '🍌' },
      { id: 'beans', label: 'beans', emoji: '🫘' },
      { id: 'lentils', label: 'lentils', emoji: '🍲' },
      { id: 'chickpeas', label: 'chickpeas', emoji: '🫘' },
      { id: 'peas', label: 'peas', emoji: '🫛' },
      { id: 'oats', label: 'oats', emoji: '🫓' },
      { id: 'quinoa', label: 'quinoa', emoji: '🌾' },
      { id: 'amaranth', label: 'amaranth', emoji: '🌾' },
      { id: 'pasta', label: 'pasta', emoji: '🍝' },
      { id: 'bread', label: 'bread', emoji: '🍞' },
      { id: 'whole_wheat_bread', label: 'whole_wheat_bread', emoji: '🍞' },
      { id: 'tortilla_corn', label: 'tortilla_corn', emoji: '🫓' },
      { id: 'tortilla_flour', label: 'tortilla_flour', emoji: '🫓' },
      { id: 'arepa', label: 'arepa', emoji: '🫓' },
      { id: 'empanada_dough', label: 'empanada_dough', emoji: '🥟' },
      { id: 'tamal_masa', label: 'tamal_masa', emoji: '🫔' },
      { id: 'taro', label: 'taro', emoji: '🍠' },
      { id: 'arracacha', label: 'arracacha', emoji: '🥔' },
      { id: 'olluco', label: 'olluco', emoji: '🥔' },
      { id: 'mote', label: 'mote', emoji: '🌽' },
      { id: 'tapioca', label: 'tapioca', emoji: '🧋' },
      { id: 'granola', label: 'granola', emoji: '🥣' },
      { id: 'rice_cakes', label: 'rice_cakes', emoji: '🍘' },
      { id: 'crackers', label: 'crackers', emoji: '🍘' },
      { id: 'couscous', label: 'couscous', emoji: '🍲' }
    ]
  },
  {
    id: 'fats', title: 'fats', min: 1,
    items: [
      { id: 'avocado', label: 'avocado', emoji: '🥑' },
      { id: 'olive_oil', label: 'olive_oil', emoji: '🫒' },
      { id: 'coconut_oil', label: 'coconut_oil', emoji: '🥥' },
      { id: 'avocado_oil', label: 'avocado_oil', emoji: '🫒' },
      { id: 'corn_oil', label: 'corn_oil', emoji: '🫒' },
      { id: 'soybean_oil', label: 'soybean_oil', emoji: '🫒' },
      { id: 'peanut_oil', label: 'peanut_oil', emoji: '🫒' },
      { id: 'butter', label: 'butter', emoji: '🧈' },
      { id: 'lard', label: 'lard', emoji: '🧈' },
      { id: 'ghee', label: 'ghee', emoji: '🧈' },
      { id: 'margarine', label: 'margarine', emoji: '🧈' },
      { id: 'peanuts', label: 'peanuts', emoji: '🥜' },
      { id: 'almonds', label: 'almonds', emoji: '🌰' },
      { id: 'walnuts', label: 'walnuts', emoji: '🌰' },
      { id: 'brazil_nuts', label: 'brazil_nuts', emoji: '🌰' },
      { id: 'cashews', label: 'cashews', emoji: '🌰' },
      { id: 'pecans', label: 'pecans', emoji: '🌰' },
      { id: 'pistachios', label: 'pistachios', emoji: '🥜' },
      { id: 'peanut_butter', label: 'peanut_butter', emoji: '🥜' },
      { id: 'almond_butter', label: 'almond_butter', emoji: '🥜' },
      { id: 'chia_seeds', label: 'chia_seeds', emoji: '🌱' },
      { id: 'flaxseeds', label: 'flaxseeds', emoji: '🌱' },
      { id: 'pumpkin_seeds', label: 'pumpkin_seeds', emoji: '🎃' },
      { id: 'sunflower_seeds', label: 'sunflower_seeds', emoji: '🌻' },
      { id: 'sesame_seeds', label: 'sesame_seeds', emoji: '🌱' },
      { id: 'olives', label: 'olives', emoji: '🫒' },
      { id: 'cheese_fat', label: 'cheese_fat', emoji: '🧀' },
      { id: 'bacon_fat', label: 'bacon_fat', emoji: '🥓' },
      { id: 'dark_chocolate', label: 'dark_chocolate', emoji: '🍫' },
      { id: 'mayo_fat', label: 'mayo_fat', emoji: '🍳' }
    ]
  },
  {
    id: 'fruits', title: 'fruits', min: 2,
    items: [
      { id: 'banana', label: 'banana', emoji: '🍌' },
      { id: 'apple', label: 'apple', emoji: '🍎' },
      { id: 'papaya', label: 'papaya', emoji: '🍈' },
      { id: 'mango', label: 'mango', emoji: '🥭' },
      { id: 'pineapple', label: 'pineapple', emoji: '🍍' },
      { id: 'watermelon', label: 'watermelon', emoji: '🍉' },
      { id: 'guava', label: 'guava', emoji: '🍐' },
      { id: 'passion_fruit', label: 'passion_fruit', emoji: '🥭' },
      { id: 'lulo', label: 'lulo', emoji: '🍊' },
      { id: 'tree_tomato', label: 'tree_tomato', emoji: '🍅' },
      { id: 'orange', label: 'orange', emoji: '🍊' },
      { id: 'lime', label: 'lime', emoji: '🍋' },
      { id: 'lemon', label: 'lemon', emoji: '🍋' },
      { id: 'grapefruit', label: 'grapefruit', emoji: '🍊' },
      { id: 'mandarin', label: 'mandarin', emoji: '🍊' },
      { id: 'grapes', label: 'grapes', emoji: '🍇' },
      { id: 'strawberries', label: 'strawberries', emoji: '🍓' },
      { id: 'blueberries', label: 'blueberries', emoji: '🫐' },
      { id: 'blackberries', label: 'blackberries', emoji: '🫐' },
      { id: 'melon', label: 'melon', emoji: '🍈' },
      { id: 'peach', label: 'peach', emoji: '🍑' },
      { id: 'plum', label: 'plum', emoji: '🍑' },
      { id: 'pear', label: 'pear', emoji: '🍐' },
      { id: 'kiwi', label: 'kiwi', emoji: '🥝' },
      { id: 'dragonfruit', label: 'dragonfruit', emoji: '🐉' },
      { id: 'soursop', label: 'soursop', emoji: '🍈' },
      { id: 'tamarind', label: 'tamarind', emoji: '🫘' },
      { id: 'mamey', label: 'mamey', emoji: '🥭' },
      { id: 'cherimoya', label: 'cherimoya', emoji: '🍈' },
      { id: 'coconut', label: 'coconut', emoji: '🥥' }
    ]
  },
  {
    id: 'veggies', title: 'veggies', min: 2,
    items: [
      { id: 'tomato', label: 'tomato', emoji: '🍅' },
      { id: 'onion', label: 'onion', emoji: '🧅' },
      { id: 'garlic_veg', label: 'garlic_veg', emoji: '🧄' },
      { id: 'bell_pepper', label: 'bell_pepper', emoji: '🫑' },
      { id: 'chili_pepper', label: 'chili_pepper', emoji: '🌶️' },
      { id: 'carrot', label: 'carrot', emoji: '🥕' },
      { id: 'broccoli', label: 'broccoli', emoji: '🥦' },
      { id: 'cauliflower', label: 'cauliflower', emoji: '🥦' },
      { id: 'cabbage', label: 'cabbage', emoji: '🥬' },
      { id: 'lettuce', label: 'lettuce', emoji: '🥬' },
      { id: 'spinach', label: 'spinach', emoji: '🥬' },
      { id: 'cilantro', label: 'cilantro', emoji: '🌿' },
      { id: 'zucchini', label: 'zucchini', emoji: '🥒' },
      { id: 'pumpkin', label: 'pumpkin', emoji: '🎃' },
      { id: 'cucumber', label: 'cucumber', emoji: '🥒' },
      { id: 'chayote', label: 'chayote', emoji: '🍐' },
      { id: 'cactus', label: 'cactus', emoji: '🌵' },
      { id: 'jicama', label: 'jicama', emoji: '🥔' },
      { id: 'green_beans', label: 'green_beans', emoji: '🫛' },
      { id: 'celery', label: 'celery', emoji: '🥬' },
      { id: 'beet', label: 'beet', emoji: '🍠' },
      { id: 'radish', label: 'radish', emoji: '🧅' },
      { id: 'eggplant', label: 'eggplant', emoji: '🍆' },
      { id: 'mushroom', label: 'mushroom', emoji: '🍄' },
      { id: 'asparagus', label: 'asparagus', emoji: '🥦' },
      { id: 'artichoke', label: 'artichoke', emoji: '🥦' },
      { id: 'leek', label: 'leek', emoji: '🧅' },
      { id: 'scallion', label: 'scallion', emoji: '🧅' },
      { id: 'swiss_chard', label: 'swiss_chard', emoji: '🥬' },
      { id: 'watercress', label: 'watercress', emoji: '🌿' }
    ]
  },
  {
    id: 'condiments', title: 'condiments', min: 1,
    items: [
      { id: 'salt', label: 'salt', emoji: '🧂' },
      { id: 'black_pepper', label: 'black_pepper', emoji: '🌶️' },
      { id: 'cumin', label: 'cumin', emoji: '🌰' },
      { id: 'oregano', label: 'oregano', emoji: '🌿' },
      { id: 'achiote', label: 'achiote', emoji: '🔴' },
      { id: 'cilantro_cond', label: 'cilantro_cond', emoji: '🌿' },
      { id: 'parsley', label: 'parsley', emoji: '🌿' },
      { id: 'garlic_cond', label: 'garlic_cond', emoji: '🧄' },
      { id: 'onion_powder', label: 'onion_powder', emoji: '🧅' },
      { id: 'paprika', label: 'paprika', emoji: '🌶️' },
      { id: 'chili_powder', label: 'chili_powder', emoji: '🌶️' },
      { id: 'hot_sauce', label: 'hot_sauce', emoji: '🔥' },
      { id: 'soy_sauce', label: 'soy_sauce', emoji: '🍶' },
      { id: 'vinegar', label: 'vinegar', emoji: '🍶' },
      { id: 'apple_cider_vinegar', label: 'apple_cider_vinegar', emoji: '🍎' },
      { id: 'lemon_juice', label: 'lemon_juice', emoji: '🍋' },
      { id: 'mustard', label: 'mustard', emoji: '🌶️' },
      { id: 'mayonnaise', label: 'mayonnaise', emoji: '🍳' },
      { id: 'ketchup', label: 'ketchup', emoji: '🍅' },
      { id: 'hogao', label: 'hogao', emoji: '🍅' },
      { id: 'salsa_verde', label: 'salsa_verde', emoji: '🟢' },
      { id: 'salsa_roja', label: 'salsa_roja', emoji: '🔴' },
      { id: 'honey', label: 'honey', emoji: '🍯' },
      { id: 'panela', label: 'panela', emoji: '🟤' },
      { id: 'cinnamon', label: 'cinnamon', emoji: '🌰' },
      { id: 'cloves', label: 'cloves', emoji: '🌰' },
      { id: 'vanilla', label: 'vanilla', emoji: '🍦' },
      { id: 'ginger', label: 'ginger', emoji: '🥔' },
      { id: 'turmeric', label: 'turmeric', emoji: '🫚' },
      { id: 'bouillon', label: 'bouillon', emoji: '🧊' }
    ]
  },
  {
    id: 'dairy', title: 'dairy', min: 0,
    items: [
      { id: 'milk', label: 'milk', emoji: '🥛' },
      { id: 'queso_fresco', label: 'queso_fresco', emoji: '🧀' },
      { id: 'queso_doble_crema', label: 'queso_doble_crema', emoji: '🧀' },
      { id: 'queso_costeno', label: 'queso_costeno', emoji: '🧀' },
      { id: 'queso_panela', label: 'queso_panela', emoji: '🧀' },
      { id: 'queso_rallado', label: 'queso_rallado', emoji: '🧀' },
      { id: 'mozzarella', label: 'mozzarella', emoji: '🧀' },
      { id: 'cheddar', label: 'cheddar', emoji: '🧀' },
      { id: 'cream_cheese', label: 'cream_cheese', emoji: '🧀' },
      { id: 'suero', label: 'suero', emoji: '🥣' },
      { id: 'crema_leche', label: 'crema_leche', emoji: '🥛' },
      { id: 'yogurt', label: 'yogurt', emoji: '🥄' },
      { id: 'greek_yogurt_dairy', label: 'greek_yogurt_dairy', emoji: '🥄' },
      { id: 'kefir', label: 'kefir', emoji: '🥛' },
      { id: 'butter_dairy', label: 'butter_dairy', emoji: '🧈' },
      { id: 'dulce_de_leche', label: 'dulce_de_leche', emoji: '🍯' },
      { id: 'condensed_milk', label: 'condensed_milk', emoji: '🥛' },
      { id: 'evaporated_milk', label: 'evaporated_milk', emoji: '🥛' },
      { id: 'powdered_milk', label: 'powdered_milk', emoji: '🥛' },
      { id: 'ice_cream', label: 'ice_cream', emoji: '🍦' },
      { id: 'lactose_free_milk', label: 'lactose_free_milk', emoji: '🥛' },
      { id: 'skim_milk', label: 'skim_milk', emoji: '🥛' },
      { id: 'almond_milk_dairy', label: 'almond_milk_dairy', emoji: '🥛' },
      { id: 'oat_milk_dairy', label: 'oat_milk_dairy', emoji: '🥛' },
      { id: 'soy_milk_dairy', label: 'soy_milk_dairy', emoji: '🥛' },
      { id: 'coconut_milk_dairy', label: 'coconut_milk_dairy', emoji: '🥥' },
      { id: 'ricotta', label: 'ricotta', emoji: '🧀' },
      { id: 'cottage_cheese_dairy', label: 'cottage_cheese_dairy', emoji: '🧀' },
      { id: 'goat_cheese', label: 'goat_cheese', emoji: '🧀' },
      { id: 'goat_milk', label: 'goat_milk', emoji: '🥛' }
    ]
  },
  {
    id: 'beverages', title: 'beverages', min: 0,
    items: [
      { id: 'water', label: 'water', emoji: '💧' },
      { id: 'sparkling_water', label: 'sparkling_water', emoji: '🫧' },
      { id: 'coffee', label: 'coffee', emoji: '☕' },
      { id: 'cafe_con_leche', label: 'cafe_con_leche', emoji: '☕' },
      { id: 'agua_panela', label: 'agua_panela', emoji: '🍹' },
      { id: 'mate', label: 'mate', emoji: '🧉' },
      { id: 'tea', label: 'tea', emoji: '🍵' },
      { id: 'hot_chocolate', label: 'hot_chocolate', emoji: '☕' },
      { id: 'jugo_naranja', label: 'jugo_naranja', emoji: '🍊' },
      { id: 'jugo_mora', label: 'jugo_mora', emoji: '🧃' },
      { id: 'jugo_lulo', label: 'jugo_lulo', emoji: '🍹' },
      { id: 'jugo_maracuya', label: 'jugo_maracuya', emoji: '🧃' },
      { id: 'jugo_guanabana', label: 'jugo_guanabana', emoji: '🥤' },
      { id: 'lemonade', label: 'lemonade', emoji: '🍋' },
      { id: 'agua_fresca', label: 'agua_fresca', emoji: '🍹' },
      { id: 'chicha', label: 'chicha', emoji: '🥤' },
      { id: 'avena_bebida', label: 'avena_bebida', emoji: '🥤' },
      { id: 'smoothie', label: 'smoothie', emoji: '🥤' },
      { id: 'protein_shake_bev', label: 'protein_shake_bev', emoji: '🧃' },
      { id: 'coconut_water', label: 'coconut_water', emoji: '🥥' },
      { id: 'sports_drink', label: 'sports_drink', emoji: '🧃' },
      { id: 'energy_drink', label: 'energy_drink', emoji: '⚡' },
      { id: 'soda', label: 'soda', emoji: '🥤' },
      { id: 'diet_soda', label: 'diet_soda', emoji: '🥤' },
      { id: 'kombucha', label: 'kombucha', emoji: '🍹' },
      { id: 'beer', label: 'beer', emoji: '🍺' },
      { id: 'wine', label: 'wine', emoji: '🍷' },
      { id: 'aguardiente', label: 'aguardiente', emoji: '🥃' },
      { id: 'bone_broth', label: 'bone_broth', emoji: '🍲' },
      { id: 'aloe_vera', label: 'aloe_vera', emoji: '🧃' }
    ]
  }
];

export const CAT_META_OB: Record<string, { gradient: [string, string]; icon: string }> = {
  proteins:   { gradient: ['#FF6B6B', '#EE5A24'], icon: '🍗' },
  carbs:      { gradient: ['#F9CA24', '#F0932B'], icon: '🍚' },
  fats:       { gradient: ['#6AB04C', '#BADC58'], icon: '🥑' },
  fruits:     { gradient: ['#EB4D8B', '#FD79A8'], icon: '🍓' },
  veggies:    { gradient: ['#00B894', '#00CEC9'], icon: '🥦' },
  condiments: { gradient: ['#FDCB6E', '#E17055'], icon: '🧂' },
  dairy:      { gradient: ['#74B9FF', '#0984E3'], icon: '🥛' },
  beverages:  { gradient: ['#A29BFE', '#6C5CE7'], icon: '☕' },
};

export const step = StyleSheet.create({
  container:        { flex: 1 },
  headerSection:    { alignItems: 'center', marginBottom: 20 },
  targetCircle:     {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10
  },
  title:            { fontSize: 22, fontWeight: '900', marginBottom: 6, textAlign: 'center' },
  sub:              { fontSize: 13, marginBottom: 24, textAlign: 'center', opacity: 0.7, paddingHorizontal: 30 },
  optionList:       { gap: 10 },
  optionCard:       {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 18,
    borderRadius: 24,
    borderWidth: 2,
  },
  iconContainer:    {
    width: 56,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  optionTitle:      { fontSize: 17, fontWeight: '900', marginBottom: 4, flexShrink: 1 },
  optionSub:        { fontSize: 13, opacity: 0.7, lineHeight: 18, flexShrink: 1 },
  radioOuter:       {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4
  },
  radioInner:       {
    width: 12,
    height: 12,
    borderRadius: 6
  },
  statsGrid:        { gap: 24, paddingBottom: 16 },
  field:            { marginBottom: 8 },
  fieldLabel:       { fontSize: 12, fontWeight: '800', letterSpacing: 1.5, marginBottom: 12, textTransform: 'uppercase', opacity: 0.6 },
  sexRow:           { flexDirection: 'row', gap: 12 },
  sexBtn:           {
    flex: 1,
    borderRadius: 24,
    borderWidth: 2,
    paddingVertical: 16,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 8,
    overflow: 'hidden'
  },
  sexIconWrap:      {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  sexLabel:         { fontSize: 17, fontWeight: '700' },
  numRow:           { flexDirection: 'row', alignItems: 'center', gap: 16 },
  numBtn:           {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  numDisplay:       {
    flex: 1,
    borderRadius: 24,
    borderWidth: 2,
    padding: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    height: 64,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  numValue:         { fontSize: 28, fontWeight: '900' },
  numUnit:          { fontSize: 14, fontWeight: '700', opacity: 0.5, marginTop: 6 },
  miniNumRow:       { flexDirection: 'row', alignItems: 'center', gap: 8 },
  miniNumBtn:       { width: 36, height: 36, borderRadius: 10, borderWidth: 1.5, justifyContent: 'center', alignItems: 'center' },
  numValueSmall:    { fontSize: 16, fontWeight: '700', minWidth: 60, textAlign: 'center' },
  categoryTitle:    { fontSize: 20, fontWeight: '900', marginBottom: 4, letterSpacing: -0.5 },
  categorySub:      { fontSize: 13, opacity: 0.6, fontWeight: '600' },
  dietGrid:         { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'flex-start' },
  dietPill:         {
    borderRadius: 20,
    borderWidth: 1.5,
    paddingRight: 12,
    paddingLeft: 4,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden'
  },
  dietPillActive:   { backgroundColor: '#7C5CFC22' },
  dietPillText:     { fontSize: 14, fontWeight: '600' },
  dietPillTextActive:{ fontWeight: '800' },
  heroGrad:         { alignItems: 'center', paddingVertical: 24, borderRadius: 20, marginBottom: 16, paddingHorizontal: 20 },
  heroIcon:         { width: 68, height: 68, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
  selectedBadge:    { marginTop: 12, paddingHorizontal: 14, paddingVertical: 5, borderRadius: 20 },
  selectedBadgeText: { color: '#FFF', fontSize: 13, fontWeight: '800' },
  searchWrap:       {
    flexDirection: 'row', alignItems: 'center',
    borderRadius: 14, borderWidth: 1.5,
    paddingHorizontal: 14, marginBottom: 16, gap: 10
  },
  searchInput:      { flex: 1, height: 48, fontSize: 16 },
  clearBtn:         { width: 26, height: 26, borderRadius: 13, justifyContent: 'center', alignItems: 'center' },
  categoryCard:     { borderRadius: 18, borderWidth: 1, marginBottom: 14, overflow: 'hidden' },
  catHeader:        { flexDirection: 'row', alignItems: 'center', padding: 14 },
  catIconWrap:      { borderRadius: 14, overflow: 'hidden' },
  catIconGrad:      { width: 46, height: 46, justifyContent: 'center', alignItems: 'center', borderRadius: 14 },
  catTitle:         { fontSize: 15, fontWeight: '800', marginBottom: 2 },
  catSub:           { fontSize: 12, fontWeight: '500', opacity: 0.7 },
  catBadge:         { paddingHorizontal: 9, paddingVertical: 3, borderRadius: 18, marginRight: 8 },
  catBadgeText:     { fontSize: 12, fontWeight: '800' },
  chevronWrap:      { width: 30, height: 30, borderRadius: 9, justifyContent: 'center', alignItems: 'center' },
  progressTrack:    { height: 3, marginHorizontal: 14, borderRadius: 2, marginBottom: 2 },
  progressBar:      { height: 3, borderRadius: 2, minWidth: 4 },
  itemsSection:     { paddingHorizontal: 12, paddingBottom: 14, paddingTop: 6 },
  selectAllBtn:     { alignSelf: 'flex-end', marginBottom: 10, paddingVertical: 3 },
  selectAllText:    { fontSize: 12, fontWeight: '700' },
  pillEmoji:        { width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 6 },
  checkDot:         { width: 15, height: 15, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginLeft: 3 },
});
