const fs = require('fs');
const path = require('path');

const files = ['en.json', 'es.json', 'fr.json', 'de.json', 'it.json', 'pt.json', 'ru.json'];

const paywallTranslations = {
  es: {
    title: "Desbloquea FitGO Pro",
    subtitle: "Tu coach personal de IA. Sin límites. Sin excusas.",
    restore: "Restaurar compras",
    continueFree: "Continuar gratis",
    mostPopular: "MÁS POPULAR",
    launchOffer: "OFERTA LANZAMIENTO",
    accessTotal: "Acceso Total Pro",
    cancelAnytime: "Cancela en cualquier momento · Sin compromisos",
    unlockNow: "Desbloquear Ahora",
    free: "Gratis",
    pro: "PRO",
    featuresTitle: "¿Qué incluye Pro?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Función Premium",
    premiumRequired: "Esta función es exclusiva para usuarios Premium. ¡Actualiza tu plan para usar el dictado por voz y la estimación con IA!",
    features: {
      coachTitle: "Coach IA Ilimitado",
      coachDesc: "Nutriólogo, Entrenador y Médico IA sin límites — 24/7",
      coachBadge: "∞ ILIMITADO",
      plannerTitle: "Planificador Nutricional IA",
      plannerDesc: "Genera menús semanales personalizados basados en tus macros",
      plannerBadge: "IA",
      scannerTitle: "Buscador y Escáner de Alimentos",
      scannerDesc: "Desbloquea la búsqueda en base de datos y escaneo de códigos de barra",
      scannerBadge: "FÁCIL",
      voiceTitle: "Dictado por Voz e IA",
      voiceDesc: "Registra tus comidas y entrenamientos hablando o describiendo libremente",
      voiceBadge: "RÁPIDO",
      directoryTitle: "Directorio Muscular Completo",
      directoryDesc: "500+ ejercicios con guías técnicas y animaciones GIFs sin anuncios",
      directoryBadge: "500+ EJS",
      colorsTitle: "Colores de Acento Premium",
      colorsDesc: "Personaliza tu perfil y toda la app con 11 colores de diseño exclusivos",
      colorsBadge: "ESTILO",
      leaguesTitle: "Ligas Élite y Squads",
      leaguesDesc: "Sube de rango en clasificaciones globales y compite en equipo sin límites",
      leaguesBadge: "COMPITE",
      historyTitle: "Historial y Exportación",
      historyDesc: "Historial completo de tu progreso desde el primer día y exportación de datos",
      historyBadge: "DATOS",
      adsTitle: "Experiencia Sin Anuncios",
      adsDesc: "Disfruta de FitGO al 100% libre de publicidad molesta o interrupciones",
      adsBadge: "VIP"
    },
    rows: {
      coach: "Coach IA",
      coachFree: "3-5 consultas / día",
      coachPro: "Ilimitado",
      scanner: "Escáner y Buscador",
      scannerFree: "Bloqueado",
      scannerPro: "Ilimitado",
      planner: "Plan Nutricional IA",
      plannerFree: "Bloqueado",
      plannerPro: "Incluido",
      voice: "Dictado por Voz",
      voiceFree: "Bloqueado",
      voicePro: "Desbloqueado",
      directory: "Directorio Muscular",
      directoryFree: "Con anuncios",
      directoryPro: "Acceso Total",
      history: "Historial de Progreso",
      historyFree: "30 días",
      historyPro: "Ilimitado",
      colors: "Colores de Diseño",
      colorsFree: "Predeterminado",
      colorsPro: "11 colores premium",
      ads: "Publicidad",
      adsFree: "Anuncios y Videos",
      adsPro: "Sin anuncios"
    }
  },
  en: {
    title: "Unlock FitGO Pro",
    subtitle: "Your personal AI coach. No limits. No excuses.",
    restore: "Restore purchases",
    continueFree: "Continue for free",
    mostPopular: "MOST POPULAR",
    launchOffer: "LAUNCH OFFER",
    accessTotal: "Total Pro Access",
    cancelAnytime: "Cancel anytime · No commitment",
    unlockNow: "Unlock Now",
    free: "Free",
    pro: "PRO",
    featuresTitle: "What's included in Pro?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Premium Feature",
    premiumRequired: "This feature is exclusive to Premium users. Upgrade your plan to use voice dictation and AI estimation!",
    features: {
      coachTitle: "Unlimited AI Coach",
      coachDesc: "AI Nutritionist, Trainer & Doctor without limits — 24/7",
      coachBadge: "∞ UNLIMITED",
      plannerTitle: "AI Nutrition Planner",
      plannerDesc: "Generate custom weekly meal plans based on your macros",
      plannerBadge: "AI",
      scannerTitle: "Food Search & Barcode Scanner",
      scannerDesc: "Unlock database search and barcode scanning",
      scannerBadge: "EASY",
      voiceTitle: "Voice Dictation & AI",
      voiceDesc: "Log meals and workouts by speaking or describing freely",
      voiceBadge: "FAST",
      directoryTitle: "Complete Muscle Directory",
      directoryDesc: "500+ exercises with technique guides and GIF animations ad-free",
      directoryBadge: "500+ EXS",
      colorsTitle: "Premium Accent Colors",
      colorsDesc: "Personalize your profile and the whole app with 11 design colors",
      colorsBadge: "STYLE",
      leaguesTitle: "Elite Leagues & Squads",
      leaguesDesc: "Rank up in global leaderboards and team up without limits",
      leaguesBadge: "COMPETE",
      historyTitle: "History & Export",
      historyDesc: "Full history of your progress from day one and data export",
      historyBadge: "DATA",
      adsTitle: "Ad-Free Experience",
      adsDesc: "Enjoy FitGO 100% free of annoying ads or interruptions",
      adsBadge: "VIP"
    },
    rows: {
      coach: "AI Coach",
      coachFree: "3-5 queries / day",
      coachPro: "Unlimited",
      scanner: "Scanner & Search",
      scannerFree: "Locked",
      scannerPro: "Unlimited",
      planner: "AI Meal Plan",
      plannerFree: "Locked",
      plannerPro: "Included",
      voice: "Voice Dictation",
      voiceFree: "Locked",
      voicePro: "Unlocked",
      directory: "Muscle Directory",
      directoryFree: "With ads",
      directoryPro: "Total Access",
      history: "Progress History",
      historyFree: "30 days",
      historyPro: "Unlimited",
      colors: "Design Colors",
      colorsFree: "Default",
      colorsPro: "11 premium colors",
      ads: "Ads",
      adsFree: "Ads & Videos",
      adsPro: "Ad-free"
    }
  },
  de: {
    title: "FitGO Pro freischalten",
    subtitle: "Ihr persönlicher KI-Coach. Keine Grenzen. Keine Ausreden.",
    restore: "Käufe wiederherstellen",
    continueFree: "Kostenlos fortfahren",
    mostPopular: "BELIEBTESTE",
    launchOffer: "EINFÜHRUNGSANGEBOT",
    accessTotal: "Vollständiger Pro-Zugang",
    cancelAnytime: "Jederzeit kündbar · Keine Verpflichtung",
    unlockNow: "Jetzt freischalten",
    free: "Gratis",
    pro: "PRO",
    featuresTitle: "Was ist in Pro enthalten?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Premium-Funktion",
    premiumRequired: "Diese Funktion ist exklusiv für Premium-Mitglieder. Aktualisieren Sie Ihren Plan, um Sprachdiktat und KI-Schätzung zu nutzen!",
    features: {
      coachTitle: "Unbegrenzter KI-Coach",
      coachDesc: "KI-Ernährungsberater, Trainer & Arzt ohne Grenzen — 24/7",
      coachBadge: "∞ UNBEGRENZT",
      plannerTitle: "KI-Ernährungsplaner",
      plannerDesc: "Erstellen Sie wöchentliche Ernährungspläne basierend auf Ihren Makros",
      plannerBadge: "KI",
      scannerTitle: "Lebensmittelsuche & Barcode-Scanner",
      scannerDesc: "Schalten Sie die Datenbanksuche und das Scannen von Barcodes frei",
      scannerBadge: "EINFACH",
      voiceTitle: "Sprachdiktat & KI",
      voiceDesc: "Protokollieren Sie Mahlzeiten und Training durch Sprechen oder freies Beschreiben",
      voiceBadge: "SCHNELL",
      directoryTitle: "Vollständiges Muskelverzeichnis",
      directoryDesc: "Über 500 Übungen mit Technikanleitungen und GIF-Animationen werbefrei",
      directoryBadge: "500+ ÜB.",
      colorsTitle: "Premium-Akzentfarben",
      colorsDesc: "Personalisieren Sie Ihr Profil und die App mit 11 exklusiven Designfarben",
      colorsBadge: "STIL",
      leaguesTitle: "Elite-Ligen & Squads",
      leaguesDesc: "Steigen Sie in globalen Ranglisten auf und spielen Sie ohne Grenzen im Team",
      leaguesBadge: "KAMPF",
      historyTitle: "Verlauf & Export",
      historyDesc: "Vollständiger Verlauf Ihres Fortschritts ab Tag eins und Datenexport",
      historyBadge: "DATEN",
      adsTitle: "Werbefreie Erfahrung",
      adsDesc: "Genießen Sie FitGO zu 100 % frei von störender Werbung oder Unterbrechungen",
      adsBadge: "VIP"
    },
    rows: {
      coach: "KI-Coach",
      coachFree: "3-5 Anfragen / Tag",
      coachPro: "Unbegrenzt",
      scanner: "Scanner & Suche",
      scannerFree: "Gesperrt",
      scannerPro: "Unbegrenzt",
      planner: "KI-Ernährungsplan",
      plannerFree: "Gesperrt",
      plannerPro: "Inbegriffen",
      voice: "Sprachdiktat",
      voiceFree: "Gesperrt",
      voicePro: "Freigeschaltet",
      directory: "Muskelverzeichnis",
      directoryFree: "Mit Werbung",
      directoryPro: "Vollzugriff",
      history: "Fortschrittsverlauf",
      historyFree: "30 Tage",
      historyPro: "Unbegrenzt",
      colors: "Designfarben",
      colorsFree: "Standard",
      colorsPro: "11 Premiumfarben",
      ads: "Werbung",
      adsFree: "Werbung & Videos",
      adsPro: "Werbefrei"
    }
  },
  fr: {
    title: "Débloquer FitGO Pro",
    subtitle: "Votre coach IA personnel. Sans limites. Sans excuses.",
    restore: "Restaurer les achats",
    continueFree: "Continuer gratuitement",
    mostPopular: "LE PLUS POPULAIRE",
    launchOffer: "OFFRE DE LANCEMENT",
    accessTotal: "Accès Complet Pro",
    cancelAnytime: "Annulez à tout moment · Sans engagement",
    unlockNow: "Débloquer Maintenant",
    free: "Gratuit",
    pro: "PRO",
    featuresTitle: "Qu'est-ce qui est inclus dans Pro ?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Fonctionnalité Premium",
    premiumRequired: "Cette fonctionnalité est exclusive aux utilisateurs Premium. Améliorez votre plan pour utiliser la dictée vocale et l'estimation par IA !",
    features: {
      coachTitle: "Coach IA illimité",
      coachDesc: "Nutritionniste, entraîneur et médecin IA sans limites — 24/7",
      coachBadge: "∞ ILLIMITÉ",
      plannerTitle: "Planificateur nutritionnel IA",
      plannerDesc: "Générez des menus hebdomadaires personnalisés basés sur vos macros",
      plannerBadge: "IA",
      scannerTitle: "Recherche et scanner d'aliments",
      scannerDesc: "Débloquez la recherche dans la base de données et le scan de codes-barres",
      scannerBadge: "FACILE",
      voiceTitle: "Dictée vocale et IA",
      voiceDesc: "Enregistrez vos repas et entraînements en parlant ou en décrivant librement",
      voiceBadge: "RAPIDE",
      directoryTitle: "Répertoire musculaire complet",
      directoryDesc: "Plus de 500 exercices avec guides techniques et animations GIF sans publicité",
      directoryBadge: "500+ EXS",
      colorsTitle: "Couleurs d'accentuation Premium",
      colorsDesc: "Personnalisez votre profil et l'application avec 11 couleurs de design exclusives",
      colorsBadge: "STYLE",
      leaguesTitle: "Ligues Élite et Squads",
      leaguesDesc: "Montez en grade dans les classements mondiaux et coopérez en équipe sans limites",
      leaguesBadge: "COMPÉTITION",
      historyTitle: "Historique et export",
      historyDesc: "Historique complet de votre progression depuis le premier jour et export de données",
      historyBadge: "DONNÉES",
      adsTitle: "Expérience sans publicité",
      adsDesc: "Profitez de FitGO à 100 % sans publicités ennuyeuses ni interruptions",
      adsBadge: "VIP"
    },
    rows: {
      coach: "Coach IA",
      coachFree: "3-5 requêtes / jour",
      coachPro: "Illimité",
      scanner: "Scanner & Recherche",
      scannerFree: "Bloqué",
      scannerPro: "Illimité",
      planner: "Plan nutritionnel IA",
      plannerFree: "Bloqué",
      plannerPro: "Inclus",
      voice: "Dictée vocale",
      voiceFree: "Bloqué",
      voicePro: "Débloqué",
      directory: "Répertoire musculaire",
      directoryFree: "Avec publicité",
      directoryPro: "Accès Total",
      history: "Historique de progression",
      historyFree: "30 jours",
      historyPro: "Illimité",
      colors: "Couleurs de design",
      colorsFree: "Par défaut",
      colorsPro: "11 couleurs premium",
      ads: "Publicité",
      adsFree: "Pubs & Vidéos",
      adsPro: "Sans pub"
    }
  },
  it: {
    title: "Sblocca FitGO Pro",
    subtitle: "Il tuo coach IA personale. Senza limiti. Senza scuse.",
    restore: "Ripristina acquisti",
    continueFree: "Continua gratis",
    mostPopular: "PIÙ POPOLARE",
    launchOffer: "OFFERTA LANCIO",
    accessTotal: "Accesso Completo Pro",
    cancelAnytime: "Disdici in qualsiasi momento · Senza vincoli",
    unlockNow: "Sblocca Ora",
    free: "Gratis",
    pro: "PRO",
    featuresTitle: "Cosa è incluso in Pro?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Funzionalità Premium",
    premiumRequired: "Questa funzionalità è esclusiva per gli utenti Premium. Aggiorna il tuo piano per usare la dettatura vocale e la stima IA!",
    features: {
      coachTitle: "Coach IA illimitato",
      coachDesc: "Nutrizionista, allenatore e medico IA senza limiti — 24/7",
      coachBadge: "∞ ILLIMITATO",
      plannerTitle: "Pianificatore nutrizionale IA",
      plannerDesc: "Genera menu settimanali personalizzati basati sui tuoi macro",
      plannerBadge: "IA",
      scannerTitle: "Ricerca e scanner di alimenti",
      scannerDesc: "Sblocca la ricerca nel database e la scansione dei codici a barre",
      scannerBadge: "FACILE",
      voiceTitle: "Dettatura vocale e IA",
      voiceDesc: "Registra pasti e allenamenti parlando o descrivendo liberamente",
      voiceBadge: "VELOCE",
      directoryTitle: "Elenco muscolare completo",
      directoryDesc: "Oltre 500 esercizi con guide tecniche e animazioni GIF senza pubblicità",
      directoryBadge: "500+ ES.",
      colorsTitle: "Colori d'accento Premium",
      colorsDesc: "Personalizza il tuo profilo e l'app con 11 colori di design esclusivi",
      colorsBadge: "STILE",
      leaguesTitle: "Leghe Élite e Squads",
      leaguesDesc: "Sali di livello nelle classifiche globali e gareggia in squadra senza limiti",
      leaguesBadge: "SFIDA",
      historyTitle: "Cronologia ed esportazione",
      historyDesc: "Cronologia completa dei progressi dal primo giorno ed esportazione dei dati",
      historyBadge: "DATI",
      adsTitle: "Esperienza senza pubblicità",
      adsDesc: "Goditi FitGO al 100% privo di fastidiosi annunci o interruzioni",
      adsBadge: "VIP"
    },
    rows: {
      coach: "Coach IA",
      coachFree: "3-5 domande / giorno",
      coachPro: "Illimitato",
      scanner: "Scanner & Ricerca",
      scannerFree: "Bloccato",
      scannerPro: "Illimitato",
      planner: "Piano nutrizionale IA",
      plannerFree: "Bloccato",
      plannerPro: "Incluso",
      voice: "Dettatura vocale",
      voiceFree: "Bloccato",
      voicePro: "Sbloccato",
      directory: "Elenco muscolare",
      directoryFree: "Con annunci",
      directoryPro: "Accesso Totale",
      history: "Cronologia progressi",
      historyFree: "30 giorni",
      historyPro: "Illimitato",
      colors: "Colori di design",
      colorsFree: "Predefinito",
      colorsPro: "11 colori premium",
      ads: "Pubblicità",
      adsFree: "Annunci & Video",
      adsPro: "Senza annunci"
    }
  },
  pt: {
    title: "Desbloquear FitGO Pro",
    subtitle: "Seu coach pessoal de IA. Sem limites. Sem desculpas.",
    restore: "Restaurar compras",
    continueFree: "Continuar gratuitamente",
    mostPopular: "MAIS POPULAR",
    launchOffer: "OFERTA DE LANÇAMENTO",
    accessTotal: "Acesso Total Pro",
    cancelAnytime: "Cancele a qualquer momento · Sem compromisso",
    unlockNow: "Desbloquear Agora",
    free: "Grátis",
    pro: "PRO",
    featuresTitle: "O que está incluído no Pro?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Recurso Premium",
    premiumRequired: "Este recurso é exclusivo para usuários Premium. Atualize seu plano para usar a digitação por voz e estimativa de IA!",
    features: {
      coachTitle: "Coach IA ilimitado",
      coachDesc: "Nutricionista, treinador e médico IA sem limites — 24/7",
      coachBadge: "∞ ILIMITADO",
      plannerTitle: "Planejador nutricional IA",
      plannerDesc: "Gere cardápios semanais personalizados com base nos seus macros",
      plannerBadge: "IA",
      scannerTitle: "Buscador e scanner de alimentos",
      scannerDesc: "Desbloqueie a busca no banco de dados e o escaneamento de código de barras",
      scannerBadge: "FÁCIL",
      voiceTitle: "Digitação por voz e IA",
      voiceDesc: "Registre suas refeições e treinos falando ou descrevendo livremente",
      voiceBadge: "RÁPIDO",
      directoryTitle: "Diretório muscular completo",
      directoryDesc: "Mais de 500 exercícios com guias de técnica e GIFs sem anúncios",
      directoryBadge: "500+ EXS",
      colorsTitle: "Cores de destaque Premium",
      colorsDesc: "Personalize seu perfil e o aplicativo com 11 cores de design exclusivas",
      colorsBadge: "ESTILO",
      leaguesTitle: "Ligas Elite e Squads",
      leaguesDesc: "Suba de nível no ranking global e dispute em equipe sem limites",
      leaguesBadge: "DISPUTE",
      historyTitle: "Histórico e exportação",
      historyDesc: "Histórico completo do seu progresso desde o primeiro dia e exportação de dados",
      historyBadge: "DADOS",
      adsTitle: "Experiência sem anúncios",
      adsDesc: "Aproveite o FitGO 100% livre de propagandas chatas ou interrupções",
      adsBadge: "VIP"
    },
    rows: {
      coach: "Coach IA",
      coachFree: "3-5 consultas / dia",
      coachPro: "Ilimitado",
      scanner: "Scanner & Busca",
      scannerFree: "Bloqueado",
      scannerPro: "Ilimitado",
      planner: "Plano nutricional IA",
      plannerFree: "Bloqueado",
      plannerPro: "Incluído",
      voice: "Digitação por voz",
      voiceFree: "Bloqueado",
      voicePro: "Desbloqueado",
      directory: "Diretório muscular",
      directoryFree: "Com anúncios",
      directoryPro: "Acesso Total",
      history: "Histórico de progresso",
      historyFree: "30 dias",
      historyPro: "Ilimitado",
      colors: "Cores de design",
      colorsFree: "Padrão",
      colorsPro: "11 cores premium",
      ads: "Publicidade",
      adsFree: "Anúncios & Vídeos",
      adsPro: "Sem anúncios"
    }
  },
  ru: {
    title: "Разблокировать FitGO Pro",
    subtitle: "Ваш личный ИИ-коуч. Без ограничений. Без оправданий.",
    restore: "Восстановить покупки",
    continueFree: "Продолжить бесплатно",
    mostPopular: "САМЫЙ ПОПУЛЯРНЫЙ",
    launchOffer: "СПЕЦИАЛЬНОЕ ПРЕДЛОЖЕНИЕ",
    accessTotal: "Полный доступ Pro",
    cancelAnytime: "Отмена в любое время · Без обязательств",
    unlockNow: "Разблокировать сейчас",
    free: "Бесплатно",
    pro: "PRO",
    featuresTitle: "Что входит в Pro?",
    vsTitle: "Free vs Pro",
    premiumFeature: "Премиум-функция",
    premiumRequired: "Эта функция доступна только для пользователей Премиум. Обновите свой тарифный план, чтобы использовать голосовой ввод и ИИ-оценку!",
    features: {
      coachTitle: "Безлимитный ИИ-коуч",
      coachDesc: "ИИ-диетолог, тренер и врач без ограничений — 24/7",
      coachBadge: "∞ БЕЗЛИМИТ",
      plannerTitle: "ИИ-планировщик питания",
      plannerDesc: "Генерация персонального недельного меню на основе ваших макросов",
      plannerBadge: "ИИ",
      scannerTitle: "Поиск продуктов и сканер штрихкодов",
      scannerDesc: "Откройте поиск по базе данных продуктов и сканирование штрихкодов",
      scannerBadge: "ПРОСТО",
      voiceTitle: "Голосовой ввод и ИИ",
      voiceDesc: "Записывайте еду и тренировки голосом или обычным описанием",
      voiceBadge: "БЫСТРО",
      directoryTitle: "Полный каталог упражнений",
      directoryDesc: "Более 500 упражнений с техникой выполнения и GIF-анимациями без рекламы",
      directoryBadge: "500+ УПР",
      colorsTitle: "Премиум-цвета акцента",
      colorsDesc: "Персонализируйте профиль и приложение с помощью 11 эксклюзивных цветов оформления",
      colorsBadge: "СТИЛЬ",
      leaguesTitle: "Элитные лиги и Squads",
      leaguesDesc: "Повышайте ранг в глобальных таблицах лидеров и соревнуйтесь в команде",
      leaguesBadge: "ТУРНИР",
      historyTitle: "История и экспорт данных",
      historyDesc: "Полная история вашего прогресса с первого дня и экспорт данных",
      historyBadge: "ДАННЫЕ",
      adsTitle: "Работа без рекламы",
      adsDesc: "Наслаждайтесь FitGO на 100% без надоедливой рекламы и пауз",
      adsBadge: "VIP"
    },
    rows: {
      coach: "ИИ-коуч",
      coachFree: "3-5 запросов / день",
      coachPro: "Безлимитно",
      scanner: "Сканер и поиск",
      scannerFree: "Заблокировано",
      scannerPro: "Безлимитно",
      planner: "ИИ-план питания",
      plannerFree: "Заблокировано",
      plannerPro: "Включено",
      voice: "Голосовой ввод",
      voiceFree: "Заблокировано",
      voicePro: "Разблокировано",
      directory: "Каталог упражнений",
      directoryFree: "С рекламой",
      directoryPro: "Полный доступ",
      history: "История прогресса",
      historyFree: "30 дней",
      historyPro: "Безлимитно",
      colors: "Цвета оформления",
      colorsFree: "Стандарт",
      colorsPro: "11 премиум-цветов",
      ads: "Реклама",
      adsFree: "Реклама и видео",
      adsPro: "Без рекламы"
    }
  }
};

const baseDir = path.join(__dirname, '..', 'i18n', 'translations');

files.forEach(file => {
  const lang = file.replace('.json', '');
  if (!paywallTranslations[lang]) {
    console.log(`No translations for ${lang}, skipping.`);
    return;
  }
  
  const filePath = path.join(baseDir, file);
  try {
    const rawData = fs.readFileSync(filePath, 'utf8');
    const content = JSON.parse(rawData);
    content.paywall = paywallTranslations[lang];
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2), 'utf8');
    console.log(`Successfully updated ${file}`);
  } catch (err) {
    console.error(`Error processing ${file}:`, err);
  }
});
